Repository bagisto/bagisto, pull requests merged in 2019-10, with the labels that each got.

#1558 Spanish translation for Shop module
  packages/Webkul/Shop/src/Resources/lang/es/app.php
Labels: Enhancement, In Progress, Shop

#1649 [Bug Fixed #1640 and #1642: Customer delete issue resolved if any inv…
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Customer/src/Http/Controllers/CustomerController.php
Labels: HACKTOBERFEST'19

#1646 [Bug Fixed #1555: order refund export related issue resolved.]
  packages/Webkul/Admin/src/Http/Controllers/ExportController.php
Labels: HACKTOBERFEST'19

#1652 [Enhancement #737: Fields added to the customer DataGrid and customer…
  packages/Webkul/Admin/src/DataGrids/AddressDataGrid.php
  packages/Webkul/Admin/src/DataGrids/CustomerDataGrid.php
  packages/Webkul/Admin/src/Http/Controllers/Customer/AddressController.php
  packages/Webkul/Admin/src/Http/routes.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/views/customers/addresses/create.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/addresses/index.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/addresses/orders/index.blade.php
  packages/Webkul/Customer/src/Repositories/CustomerAddressRepository.php
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/publishable/assets/images/Icon-Listing.svg
  packages/Webkul/Ui/publishable/assets/js/ui.js
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
  packages/Webkul/Ui/src/Resources/assets/images/Icon-Listing.svg
  packages/Webkul/Ui/src/Resources/assets/sass/app.scss
  packages/Webkul/Ui/src/Resources/assets/sass/icons.scss
Labels: Enhancement, HACKTOBERFEST'19

#1659 [Enhancement #1232 : Added option for showing records per page in con…
  packages/Webkul/Admin/src/Config/system.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Ui/src/DataGrid/DataGrid.php
Labels: Enhancement, HACKTOBERFEST'19

#1654 issue #1613 fixed
  packages/Webkul/Shop/src/Resources/views/emails/customer/registration.blade.php
Labels: HACKTOBERFEST'19

#1651 Bug Fixed #1645: No confirm password action when customer is deleting…
  packages/Webkul/Customer/src/Http/Controllers/CustomerController.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/views/customers/account/profile/index.blade.php
Labels: HACKTOBERFEST'19

#1650 [Bug Fixed #1219 ] & [Enhancement #1182] Fixed
  packages/Webkul/API/Http/Controllers/Shop/SessionController.php
  packages/Webkul/Admin/src/Resources/views/users/sessions/create.blade.php
  packages/Webkul/Shop/src/Http/Controllers/OnepageController.php
  packages/Webkul/Shop/src/Http/routes.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-checkout.blade.php
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/session/index.blade.php
  packages/Webkul/User/src/Http/Controllers/SessionController.php
Labels: HACKTOBERFEST'19
