Repository bagisto/bagisto, pull requests merged in 2022-12, with the labels that each got.

#7138 Issue Fixed [#7137]
  packages/Webkul/Customer/src/Http/Controllers/WishlistController.php
  packages/Webkul/Shop/src/Http/Controllers/CartController.php
  packages/Webkul/Shop/src/Http/Controllers/ProductController.php
  packages/Webkul/Velocity/src/Http/Controllers/Shop/CartController.php
  packages/Webkul/Velocity/src/Http/Controllers/Shop/ComparisonController.php
Labels: Change Request

#7165 Issue fixed #7160
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/js/UI/components/mini-cart.vue
Labels: Getting Fixed

#7184 Update app.php file
  packages/Webkul/BookingProduct/src/Resources/lang/it/app.php
Labels: Getting Fixed

#7183 Translation issue fix for admin
  packages/Webkul/Velocity/src/Http/Controllers/Admin/ConfigurationController.php
  packages/Webkul/Velocity/src/Http/Controllers/Admin/ContentController.php
  packages/Webkul/Velocity/src/Resources/lang/ar/app.php
  packages/Webkul/Velocity/src/Resources/lang/en/app.php
  packages/Webkul/Velocity/src/Resources/lang/es/app.php
  packages/Webkul/Velocity/src/Resources/lang/fr/app.php
  packages/Webkul/Velocity/src/Resources/lang/nl/app.php
  packages/Webkul/Velocity/src/Resources/lang/tr/app.php
Labels: Getting Fixed

#7188 Performance - Dashboard Controller
  packages/Webkul/Admin/src/Http/Controllers/DashboardController.php
Labels: Critical, In Testing

#7167 Issue Fixed #6991
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
  packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking.blade.php
  packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/event.blade.php
  packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/slots.blade.php
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/publishable/assets/js/ui.js
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
  packages/Webkul/Ui/src/Resources/assets/sass/app.scss
Labels: Getting Fixed
