Repository bagisto/bagisto, pull requests merged in 2022-11, with the labels that each got.

#6971 Notificatio-ui-issue-fixed
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/publishable/assets/js/admin.js.LICENSE.txt
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
Labels: Getting Fixed, Hacktoberfest

#7069 feat: added Hindi translation to `/packages/Webkul/Core/src/Resources/lang`
  packages/Webkul/Core/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Core/src/Resources/lang/hi_IN/validation.php
  packages/Webkul/Tax/src/Resources/lang/hi_IN/app.php
Labels: Getting Fixed

#7071 Paypal smart button exception trans corrections.
  packages/Webkul/Paypal/src/Http/Controllers/SmartButtonController.php
  packages/Webkul/Paypal/src/Http/Controllers/StandardController.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/ben/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
Labels: Getting Fixed

#7056 Add Ukrainian localisation for UI app, Product App, Booking App
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Ui/src/Resources/lang/uk/app.php
  packages/Webkul/Ui/src/Resources/lang/uk/form.php
  packages/Webkul/Velocity/src/Resources/lang/ar/app.php
  packages/Webkul/Velocity/src/Resources/lang/ben/app.php
  packages/Webkul/Velocity/src/Resources/lang/de/app.php
  packages/Webkul/Velocity/src/Resources/lang/en/app.php
  packages/Webkul/Velocity/src/Resources/lang/es/app.php
  packages/Webkul/Velocity/src/Resources/lang/fa/app.php
  packages/Webkul/Velocity/src/Resources/lang/fr/app.php
  packages/Webkul/Velocity/src/Resources/lang/he/app.php
  packages/Webkul/Velocity/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Velocity/src/Resources/lang/it/app.php
  packages/Webkul/Velocity/src/Resources/lang/ja/app.php
  packages/Webkul/Velocity/src/Resources/lang/nl/app.php
  packages/Webkul/Velocity/src/Resources/lang/pl/app.php
  packages/Webkul/Velocity/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Velocity/src/Resources/lang/ru/app.php
  packages/Webkul/Velocity/src/Resources/lang/sin/app.php
  packages/Webkul/Velocity/src/Resources/lang/tr/app.php
  packages/Webkul/Velocity/src/Resources/lang/uk/app.php
  packages/Webkul/Velocity/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Velocity/src/Resources/views/shop/customers/signup/index.blade.php
Labels: Getting Fixed, Hacktoberfest

#7052 i18n: ES - Add missing translations
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Core/src/Resources/lang/es/validation.php
  packages/Webkul/Paypal/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Tax/src/Resources/lang/es/app.php
  packages/Webkul/Ui/src/Resources/lang/es/app.php
  packages/Webkul/Velocity/src/Resources/lang/es/app.php
Labels: Getting Fixed, Hacktoberfest

#7035 Issue Fixed #6993
  packages/Webkul/BookingProduct/src/Resources/views/admin/catalog/products/accordians/booking/event.blade.php
Labels: Getting Fixed, Hacktoberfest

#6920 issue #6913 fixed
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/images/flags/default-locale-image.png
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/js/UI/components/header-mobile.vue
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/header/mobile.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/top-nav/locale-currency.blade.php
Labels: Getting Fixed, Hacktoberfest

#7102 Added status badge
  packages/Webkul/Admin/src/DataGrids/CategoryDataGrid.php
Labels: Getting Fixed

#7066 Bengali translation ✅
  lang/bn/auth.php
  lang/bn/pagination.php
  lang/bn/passwords.php
  lang/bn/validation.php
Labels: Getting Fixed, Hacktoberfest

#7050 Italian translation
  lang/it/auth.php
  lang/it/pagination.php
  lang/it/passwords.php
  lang/it/validation.php
Labels: Getting Fixed, Hacktoberfest

#7044 Few changes in RU locales for Admin app. Fix typos in translation keys
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/ben/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/create.blade.php
  packages/Webkul/CartRule/src/Http/Controllers/CartRuleCouponController.php
  packages/Webkul/Ui/src/Resources/lang/ru/app.php
  packages/Webkul/Ui/src/Resources/lang/ru/form.php
Labels: Getting Fixed

#7118 Fixed Issue [#7117]
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss
Labels: Getting Fixed

#7098 [Fixed: reset password route was missing.]
  packages/Webkul/Shop/src/Resources/views/customers/signup/forgot-password.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/customer/forget-password.blade.php
  packages/Webkul/Shop/src/Routes/customer-routes.php
  packages/Webkul/Velocity/src/Resources/views/shop/customers/signup/forgot-password.blade.php
Labels: Getting Fixed

#7092 Issue Fixed #7091
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
  packages/Webkul/Ui/src/Resources/assets/sass/app.scss
Labels: Getting Fixed

#7090 fixed the translation
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
Labels: Getting Fixed

#7081 CMS page-ui issue fixed
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
Labels: Getting Fixed

#7108 Fixed datagrid mass action issue
  packages/Webkul/Category/src/Http/Controllers/CategoryController.php
  packages/Webkul/Product/src/Http/Controllers/ProductController.php
  packages/Webkul/Product/src/Http/Controllers/ReviewController.php
  packages/Webkul/Ui/publishable/assets/js/ui.js
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
  packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/partials/datagrid-table.vue
  packages/Webkul/Ui/src/Resources/views/datagrid/partials/mass-action-header.blade.php
Labels: Getting Fixed, Conflicts

#7112 Table content issue for RTL view customer panel #7105
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss
Labels: Getting Fixed

#7095 add decimal to currency
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/ben/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/settings/currencies/create.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/currencies/edit.blade.php
  packages/Webkul/Core/src/Core.php
  packages/Webkul/Core/src/Database/Migrations/2022_11_09_184539_add_decimal_columns_to_currency_table.php
  packages/Webkul/Core/src/Models/Currency.php
Labels: Getting Fixed

#7124 Issue #7085 Fixed
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/bn/app.php
  packages/Webkul/Core/src/Resources/lang/bn/app.php
  packages/Webkul/Core/src/Resources/lang/bn/validation.php
  packages/Webkul/Customer/src/Resources/lang/bn/app.php
  packages/Webkul/SocialLogin/src/Resources/lang/bn/app.php
  packages/Webkul/Tax/src/Resources/lang/bn/app.php
  packages/Webkul/Ui/src/Resources/lang/bn/app.php
  packages/Webkul/Ui/src/Resources/lang/bn/form.php
  packages/Webkul/Velocity/src/Resources/lang/bn/app.php
Labels: Critical

#6973 [Updated: performed changes for email templates.]
  config/app.php
  packages/Webkul/Admin/src/Traits/Mails.php
  packages/Webkul/BookingProduct/src/Type/Booking.php
  packages/Webkul/Core/src/Core.php
  packages/Webkul/Core/src/Traits/PDFHandler.php
  packages/Webkul/Customer/src/Models/Wishlist.php
  packages/Webkul/Shop/src/Resources/views/emails/admin/registration.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/customer/registration.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/new-admin-order.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/new-inventorysource-shipment.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/new-invoice.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/new-order.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/new-refund.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/new-shipment.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/order-cancel-admin.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/order-cancel.blade.php
  packages/Webkul/Ui/src/Resources/views/datagrid/table.blade.php
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/header/mobile.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/search/search.blade.php
Labels: Getting Fixed, Hacktoberfest

#7127 Added selective indexing
  packages/Webkul/Product/src/Console/Commands/Indexer.php
  packages/Webkul/Product/src/Helpers/Indexers/AbstractIndexer.php
  packages/Webkul/Product/src/Helpers/Indexers/Price.php
  packages/Webkul/Product/src/Helpers/Indexers/Price/AbstractType.php
Labels: Getting Fixed

#7131 Ticket Booking UI Description Issue #7128
  packages/Webkul/BookingProduct/src/Resources/views/shop/default/products/view/booking/event.blade.php
  packages/Webkul/BookingProduct/src/Resources/views/shop/velocity/products/view/booking/event.blade.php
Labels: Getting Fixed

#7126 Tool tip added for booking product on table and calendar view icon #6987
  packages/Webkul/BookingProduct/src/Resources/lang/ar/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/bn/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/de/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/en/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/es/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/fa/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/fr/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/he/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/hi_IN/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/it/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/ja/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/nl/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/pl/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/pt_BR/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/ru/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/sin/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/tr/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/uk/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/zh_CN/app.php
  packages/Webkul/BookingProduct/src/Resources/views/admin/sales/bookings/index/view-swither.blade.php
Labels: Getting Fixed

#7134 Fixed Issue [#7133]
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/publishable/assets/js/admin.js.LICENSE.txt
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
Labels: Getting Fixed

#7129 Product view by URL (pasting slug) without enabling product view individually #6756
  packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
Labels: Getting Fixed

#7141 Issue #6972 fixed
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
  packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/add-to-cart.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/wishlist.blade.php
Labels: Getting Fixed

#6876 Invoice design updates #6838
  packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/orders/pdf.blade.php
Labels: Getting Fixed

#7145 Fixed URL Issue #6771
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/js/app.js
  packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/bundle-items.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/grouped-products.blade.php
  packages/Webkul/Admin/src/Resources/views/layouts/master.blade.php
Labels: Getting Fixed

#7140 feature : add login as customer to admin customer grid
  packages/Webkul/Admin/src/DataGrids/CustomerDataGrid.php
  packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerController.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Routes/customers-routes.php
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/publishable/assets/images/icon-lock.svg
  packages/Webkul/Ui/src/Resources/assets/images/icon-lock.svg
  packages/Webkul/Ui/src/Resources/assets/sass/main/_icons.scss
Labels: Getting Fixed

#7146 Fixed For Configurable And Grouped Product #6953
  packages/Webkul/Product/src/Type/AbstractType.php
  packages/Webkul/Product/src/Type/Grouped.php
Labels: Getting Fixed

#6768 Multiple requests
  packages/Webkul/Shop/src/Resources/assets/js/components/header-compare-with-badge.vue
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/js/UI/components/header-compare-with-badge.vue
  packages/Webkul/Velocity/src/Resources/assets/js/UI/components/header-wishlist-with-badge.vue
  packages/Webkul/Velocity/src/Resources/assets/js/UI/components/product-compare.vue
  packages/Webkul/Velocity/src/Resources/assets/js/app.js
  packages/Webkul/Velocity/src/Resources/assets/sass/app.scss
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/header/index.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/master.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/particals/header-compts.blade.php
Labels: Critical

#7147 Issue Fixed #7080
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/src/Resources/assets/sass/app.scss
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/bundle-items.blade.php
Labels: Getting Fixed
