Repository bagisto/bagisto, pull requests merged in 2022-10, with the labels that each got.

#6806 Removed unnecessary filter label from data grid #6782
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/publishable/assets/js/ui.js
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
  packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/partials/datagrid-filter-tag.vue
Labels: Getting Fixed, Hacktoberfest

#6805 Issue #6775 fixed
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/js/jquery-ez-plus.js
  packages/Webkul/Velocity/publishable/assets/js/manifest.js
  packages/Webkul/Velocity/publishable/assets/js/velocity-core.js
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss
Labels: Getting Fixed, Hacktoberfest

#6794 Issue #6770 Fixed
  packages/Webkul/Product/src/Repositories/ProductRepository.php
Labels: Getting Fixed, Hacktoberfest

#6803 Issue #6797 fixed
  packages/Webkul/Shop/src/Resources/views/layouts/footer/footer.blade.php
Labels: Getting Fixed, Hacktoberfest

#6819 Product price indexing
  app/Console/Kernel.php
  composer.json
  composer.lock
  database/migrations/2022_10_04_144444_create_job_batches_table.php
  packages/Webkul/BookingProduct/src/Type/Booking.php
  packages/Webkul/CatalogRule/src/Helpers/CatalogRuleProductPrice.php
  packages/Webkul/CatalogRule/src/Repositories/CatalogRuleProductPriceRepository.php
  packages/Webkul/Core/src/Eloquent/Repository.php
  packages/Webkul/Customer/src/Models/Customer.php
  packages/Webkul/Product/src/Console/Commands/PriceIndexer.php
  packages/Webkul/Product/src/Console/Commands/PriceUpdate.php
  packages/Webkul/Product/src/Contracts/ProductPriceIndex.php
  packages/Webkul/Product/src/Database/Migrations/2022_10_03_144232_create_product_price_indices_table.php
  packages/Webkul/Product/src/Helpers/ConfigurableOption.php
  packages/Webkul/Product/src/Helpers/PriceIndexer.php
  packages/Webkul/Product/src/Helpers/PriceIndexer/AbstractPriceIndex.php
  packages/Webkul/Product/src/Helpers/PriceIndexer/Bundle.php
  packages/Webkul/Product/src/Helpers/PriceIndexer/Configurable.php
  packages/Webkul/Product/src/Helpers/PriceIndexer/Downloadable.php
  packages/Webkul/Product/src/Helpers/PriceIndexer/Grouped.php
  packages/Webkul/Product/src/Helpers/PriceIndexer/Simple.php
  packages/Webkul/Product/src/Helpers/PriceIndexer/Virtual.php
  packages/Webkul/Product/src/Helpers/Review.php
  packages/Webkul/Product/src/Jobs/PriceIndexer.php
  packages/Webkul/Product/src/Listeners/Attribute.php
  packages/Webkul/Product/src/Listeners/Product.php
  packages/Webkul/Product/src/Models/Product.php
  packages/Webkul/Product/src/Models/ProductBundleOptionProduct.php
  packages/Webkul/Product/src/Models/ProductCustomerGroupPrice.php
  packages/Webkul/Product/src/Models/ProductFlat.php
  packages/Webkul/Product/src/Models/ProductPriceIndex.php
  packages/Webkul/Product/src/Models/ProductPriceIndexProxy.php
  packages/Webkul/Product/src/Providers/EventServiceProvider.php
  packages/Webkul/Product/src/Providers/ModuleServiceProvider.php
  packages/Webkul/Product/src/Providers/ProductServiceProvider.php
  packages/Webkul/Product/src/Repositories/ProductCustomerGroupPriceRepository.php
  packages/Webkul/Product/src/Repositories/ProductPriceIndexRepository.php
  packages/Webkul/Product/src/Repositories/ProductRepository.php
  packages/Webkul/Product/src/Type/AbstractType.php
  packages/Webkul/Product/src/Type/Bundle.php
  packages/Webkul/Product/src/Type/Configurable.php
  packages/Webkul/Product/src/Type/Downloadable.php
  packages/Webkul/Product/src/Type/Grouped.php
  packages/Webkul/Product/src/Type/Simple.php
  packages/Webkul/Product/src/Type/Virtual.php
  packages/Webkul/Shop/src/Resources/views/products/list/card.blade.php
  packages/Webkul/Shop/src/Resources/views/products/reviews/index.blade.php
  packages/Webkul/User/src/Models/Admin.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/list/card.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/list/layered-navigation.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/view.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/view/reviews.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/view/stock.blade.php
  storage/logs/.gitignore
Labels: Critical, In Testing

#6802 Issue #6776 fixed
  packages/Webkul/Ui/publishable/assets/js/ui.js
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
  packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/partials/datagrid-filter-tag.vue
  packages/Webkul/Ui/src/Resources/lang/ar/app.php
  packages/Webkul/Ui/src/Resources/lang/de/app.php
Labels: Getting Fixed, Hacktoberfest

#6839 Issue Fixed #6822
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/app.scss
  packages/Webkul/Velocity/src/Resources/views/shop/customers/account/orders/view.blade.php
Labels: Getting Fixed, Hacktoberfest

#6845 Issue #6844 fixed
  packages/Webkul/Shop/src/DataGrids/DownloadableProductDataGrid.php
Labels: Hacktoberfest

#6791 Issue #6747 fixed
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
Labels: Hacktoberfest

#6827 Add Page Button on CMS Style on Mobile View (Issue Fixed #6821)
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_mobile.scss
Labels: Getting Fixed, Hacktoberfest

#6855 Make tables responsive on view order page
  packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
Labels: Getting Fixed, Hacktoberfest

#6783 Clear ALL button issues #6778
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/js/jquery-ez-plus.js
  packages/Webkul/Velocity/publishable/assets/js/manifest.js
  packages/Webkul/Velocity/publishable/assets/js/velocity-core.js
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/datagrid.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss
Labels: Getting Fixed

#6795 wish-list icon spacing issue on compare product's page #6793
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss
Labels: Getting Fixed, Hacktoberfest

#6872 Add missing space around content on subscriber page
  packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/subscribers/edit.blade.php
Labels: Getting Fixed, Hacktoberfest

#6816 issue #6779 fixed
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/app.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/cart/index.blade.php
Labels: Getting Fixed, Hacktoberfest

#6809 Issue Fixed #6799 (Relevant Message Shown now when User is inactive)
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
Labels: Getting Fixed, Hacktoberfest

#6853 Fixed #6820 - Customer Group Price adding details in price section is…
  packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/customer-group-price.blade.php
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/src/Resources/assets/sass/app.scss
Labels: Getting Fixed, Hacktoberfest

#6870 Issue Fixed #6864
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
Labels: Getting Fixed, Hacktoberfest

#6874 Make proper round corners for notification dropdown
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
  packages/Webkul/Ui/src/Resources/assets/sass/app.scss
Labels: Getting Fixed, Hacktoberfest

#6875 Issue #6777 fixed
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss
Labels: Getting Fixed, Hacktoberfest

#6906 Issue 6905 Fixed
  packages/Webkul/Admin/src/Resources/views/sales/invoices/create.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/refunds/create.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php
Labels: Getting Fixed, Hacktoberfest

#6902 Enhancement: Customer address validation updates.
  packages/Webkul/Admin/src/Http/Controllers/Customer/AddressController.php
  packages/Webkul/Customer/src/Http/Requests/CustomerAddressRequest.php
Labels: Getting Fixed, Hacktoberfest

#6883 Make tables responsive on Families page
  packages/Webkul/Admin/src/Resources/views/catalog/families/create.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/families/edit.blade.php
Labels: Getting Fixed, Hacktoberfest

#6818 Feature : New issue templates with .yml files 🛠
  .github/ISSUE_TEMPLATE/1_Bug_report.md
  .github/ISSUE_TEMPLATE/2_Feature_request.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Getting Fixed, Hacktoberfest

#6792 cart item parent image showing issue if child image not uploaded #6765
  packages/Webkul/Product/src/Type/Configurable.php
Labels: Getting Fixed, Hacktoberfest

#6890 Issue Fixed #6889
  packages/Webkul/Shop/src/Resources/lang/ben/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
Labels: Getting Fixed, Hacktoberfest

#6899 [Fixed: #6873 The product should not be out of stock if the quantity …
  packages/Webkul/Product/src/Http/Controllers/ProductController.php
Labels: Getting Fixed, Hacktoberfest

#6904 [Fixed: #6434 & #6758 Translation issue payment methods on the checkout page.]
  packages/Webkul/Payment/src/Config/system.php
  packages/Webkul/Paypal/src/Config/system.php
  packages/Webkul/Shipping/src/Config/system.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/payment.blade.php
Labels: Getting Fixed, Hacktoberfest

#6891 [Fixed: #6814 Mobile View -> Product Special Price Default Text and C…
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/publishable/assets/js/admin.js.LICENSE.txt
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_mobile.scss
Labels: Getting Fixed, Hacktoberfest

#6885 [Updated: Downloadable Product Link & Simple models updated.]
  packages/Webkul/Product/src/Models/ProductDownloadableLink.php
  packages/Webkul/Product/src/Models/ProductDownloadableSample.php
Labels: Getting Fixed, Hacktoberfest

#6915 Issue 6914 Fixed
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
Labels: Getting Fixed, Hacktoberfest

#6878 add formatDate for convert date
  packages/Webkul/Admin/src/DataGrids/CustomersInvoicesDataGrid.php
  packages/Webkul/Admin/src/Resources/views/sales/invoices/create.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/invoices/view.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/refunds/create.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/refunds/view.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/shipments/view.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/transactions/view.blade.php
  packages/Webkul/Core/src/Core.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/new-admin-order.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/new-inventorysource-shipment.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/new-invoice.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/new-order.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/new-refund.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/new-shipment.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/order-cancel-admin.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/sales/order-cancel.blade.php
  packages/Webkul/Ui/src/DataGrid/Traits/ProvideCollection.php
Labels: Hacktoberfest, Change Request

#6911 Fixed content floating on mobile view.
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_sales.scss
Labels: Getting Fixed, Hacktoberfest

#6894 Add some missed RU translations. #6892
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
Labels: Getting Fixed, Hacktoberfest

#6919 Issue #6908 fixed
  packages/Webkul/Velocity/src/Resources/lang/ar/app.php
  packages/Webkul/Velocity/src/Resources/lang/ben/app.php
  packages/Webkul/Velocity/src/Resources/lang/de/app.php
  packages/Webkul/Velocity/src/Resources/lang/en/app.php
  packages/Webkul/Velocity/src/Resources/lang/es/app.php
  packages/Webkul/Velocity/src/Resources/lang/fa/app.php
  packages/Webkul/Velocity/src/Resources/lang/fr/app.php
  packages/Webkul/Velocity/src/Resources/lang/he/app.php
  packages/Webkul/Velocity/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Velocity/src/Resources/lang/it/app.php
  packages/Webkul/Velocity/src/Resources/lang/ja/app.php
  packages/Webkul/Velocity/src/Resources/lang/nl/app.php
  packages/Webkul/Velocity/src/Resources/lang/pl/app.php
  packages/Webkul/Velocity/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Velocity/src/Resources/lang/ru/app.php
  packages/Webkul/Velocity/src/Resources/lang/sin/app.php
  packages/Webkul/Velocity/src/Resources/lang/tr/app.php
  packages/Webkul/Velocity/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/header/mobile.blade.php
Labels: Getting Fixed, Hacktoberfest

#6901 fixed Inventory Updated issues #6900
  packages/Webkul/Product/src/Http/Requests/InventoryRequest.php
Labels: Getting Fixed, Hacktoberfest

#6912 Issue #6907 Fixed
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
Labels: Getting Fixed, Hacktoberfest

#6804 [Added: view render event to CMS blade file.]
  packages/Webkul/Admin/src/Resources/views/cms/create.blade.php
  packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
Labels: Hacktoberfest, In Testing

#6925 [Fixed: #6884]
  packages/Webkul/Admin/src/Http/Controllers/Customer/AddressController.php
  packages/Webkul/Admin/src/Resources/views/customers/addresses/create.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
Labels: Hacktoberfest, Change Request

#6935 fix Farsi - Persian Transalation issue
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/fa/app.php
  packages/Webkul/Core/src/Resources/lang/fa/validation.php
  packages/Webkul/Paypal/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Ui/src/Resources/lang/fa/app.php
  packages/Webkul/Velocity/src/Resources/lang/fa/app.php
Labels: Getting Fixed, Hacktoberfest

#6934 Arabic Transaltion issue: Fixed
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Customer/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Tax/src/Resources/lang/ar/app.php
  packages/Webkul/Ui/src/Resources/lang/ar/app.php
  packages/Webkul/Ui/src/Resources/lang/ar/form.php
  packages/Webkul/Velocity/src/Resources/lang/ar/app.php
Labels: Getting Fixed, Hacktoberfest

#6939 Farsi translation corrected
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
Labels: Getting Fixed, Hacktoberfest

#6937 Fix Transalation issue for Simplified Chines Locale
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Ui/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Velocity/src/Resources/lang/zh_CN/app.php
Labels: Getting Fixed, Hacktoberfest

#6928 [Fixed: #6755]
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
Labels: Getting Fixed, Hacktoberfest

#6918 Issue #6917 fixed
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
Labels: Getting Fixed, Hacktoberfest

#6817 Added Footer links for velocity #6757
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/footer/footer-links.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/footer/footer-links/footer-left.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/footer/footer-links/footer-middle.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/footer/footer-links/footer-right.blade.php
Labels: Getting Fixed, Hacktoberfest

#6766 Product link visible even when product individual visibility is inactive on admin #6756
  packages/Webkul/Admin/src/DataGrids/ProductDataGrid.php
Labels: Getting Fixed

#6731 Product searching on bundle products with name and sku #6729
  packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/bundle-items.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/grouped-products.blade.php
Labels: Getting Fixed

#6941 [Fixed: #6761]
  packages/Webkul/Core/src/Core.php
Labels: Getting Fixed, Hacktoberfest

#6865 Update app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
Labels: Getting Fixed, Hacktoberfest

#6931 [Fixed: #6738]
  packages/Webkul/Velocity/src/Database/Seeders/VelocityMetaDataSeeder.php
  packages/Webkul/Velocity/src/Resources/lang/ar/app.php
  packages/Webkul/Velocity/src/Resources/lang/ben/app.php
  packages/Webkul/Velocity/src/Resources/lang/de/app.php
  packages/Webkul/Velocity/src/Resources/lang/en/app.php
  packages/Webkul/Velocity/src/Resources/lang/es/app.php
  packages/Webkul/Velocity/src/Resources/lang/fa/app.php
  packages/Webkul/Velocity/src/Resources/lang/fr/app.php
  packages/Webkul/Velocity/src/Resources/lang/he/app.php
  packages/Webkul/Velocity/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Velocity/src/Resources/lang/it/app.php
  packages/Webkul/Velocity/src/Resources/lang/ja/app.php
  packages/Webkul/Velocity/src/Resources/lang/nl/app.php
  packages/Webkul/Velocity/src/Resources/lang/pl/app.php
  packages/Webkul/Velocity/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Velocity/src/Resources/lang/ru/app.php
  packages/Webkul/Velocity/src/Resources/lang/sin/app.php
  packages/Webkul/Velocity/src/Resources/lang/tr/app.php
  packages/Webkul/Velocity/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Velocity/src/Resources/views/shop/home/advertisements/advertisement-one.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/home/advertisements/advertisement-two.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/home/category-with-custom-option.blade.php
Labels: Getting Fixed, Hacktoberfest

#6950 README.md typos
  README.md
Labels: Getting Fixed, Hacktoberfest

#6752 [Fixed] PDF translation Arabic #6749
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
Labels: Getting Fixed

#6958 Issue #6957 Fixed
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
Labels: Getting Fixed, Hacktoberfest

#6938 Removed ProductRepository from Velocity
  packages/Webkul/Velocity/src/Http/Controllers/Shop/ShopController.php
  packages/Webkul/Velocity/src/Repositories/Product/ProductRepository.php
Labels: Hacktoberfest, In Testing

#6940 Add RU locale for BookingProduct app
  packages/Webkul/BookingProduct/src/Resources/lang/ru/app.php
Labels: Getting Fixed, Hacktoberfest

#6948 Fix all references to `comma-seperated` attribute and strings
  packages/Webkul/Admin/src/Config/system.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/ben/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
Labels: Getting Fixed, Hacktoberfest

#6949 Fix all references to `in-maitainace` error attribute
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/ben/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/errors/503.blade.php
  packages/Webkul/Shop/src/Resources/views/errors/503.blade.php
Labels: Getting Fixed, Hacktoberfest

#6952 Fix additional Simplified Chinese translation issues
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Customer/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Velocity/src/Resources/lang/zh_CN/app.php
Labels: Getting Fixed, Hacktoberfest

#6887 Issue Fixed #6886 (Locale Dropdown Overlapping on Mobile View issue fixed)
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/publishable/assets/js/ui.js
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
  packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/datagrid-plus.vue
  packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/partials/datagrid-extra-filters.vue
  packages/Webkul/Ui/src/Resources/assets/sass/app.scss
Labels: Getting Fixed, Hacktoberfest

#6881 [Fixed Issue] #6880
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/js/UI/components/product-quick-view.vue
Labels: Getting Fixed, Hacktoberfest

#6923 Issue #6898
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/app.scss
  packages/Webkul/Velocity/src/Resources/views/shop/products/list/toolbar.blade.php
Labels: Getting Fixed, Hacktoberfest

#6963 Issue #6955 fixed
  packages/Webkul/Velocity/src/Resources/views/shop/customers/session/index.blade.php
Labels: Getting Fixed, Hacktoberfest

#6964 Remove php pusher from composer file
  composer.json
  composer.lock
Labels: Hacktoberfest, In Testing

#6965 fix mini cart issue
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
Labels: Getting Fixed, Hacktoberfest

#6866 Issue Fixed #6860 (In Catalog Products, Weight should not be negative)
  packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/field-types/text.blade.php
Labels: Getting Fixed, Hacktoberfest

#6961 Fix Spanish translation issues
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
Labels: Getting Fixed, Hacktoberfest

#6842 Fixed Issue #6841
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
Labels: Getting Fixed, Hacktoberfest

#6916 Save button overriding issue for setting menu on mobile view.
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
Labels: Getting Fixed, Hacktoberfest

#6969 [Fixed Issue] #6793
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
Labels: Getting Fixed, Hacktoberfest

#6970 Dutch translation-correction
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
Labels: Getting Fixed, Hacktoberfest

#6960 Issue Fixed #6959
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
Labels: Getting Fixed, Hacktoberfest

#6979 Issue #6976 fixed
  packages/Webkul/Product/src/Helpers/Indexer.php
  packages/Webkul/Product/src/Listeners/Product.php
Labels: In Testing

#6983 Issue #6840 Fixed
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/shared.scss
Labels: Getting Fixed, Hacktoberfest

#6962 Fix bengali locale issue
  packages/Webkul/Admin/src/Resources/lang/ben/app.php
  packages/Webkul/BookingProduct/src/Resources/lang/ben/app.php
  packages/Webkul/Core/src/Resources/lang/ben/app.php
  packages/Webkul/Core/src/Resources/lang/ben/validation.php
  packages/Webkul/Customer/src/Resources/lang/ben/app.php
  packages/Webkul/Paypal/src/Resources/lang/ben/app.php
  packages/Webkul/Shop/src/Resources/lang/ben/app.php
  packages/Webkul/SocialLogin/src/Resources/lang/ben/app.php
  packages/Webkul/Tax/src/Resources/lang/ben/app.php
  packages/Webkul/Ui/src/Resources/lang/ben/app.php
  packages/Webkul/Ui/src/Resources/lang/ben/form.php
  packages/Webkul/Velocity/src/Resources/lang/ben/app.php
Labels: Getting Fixed, Hacktoberfest

#7064 Fixed UI of Configuration
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
Labels: Getting Fixed, Hacktoberfest

#7063 Fixed spacing issue
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/src/Resources/assets/sass/includes/components.scss
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
Labels: Getting Fixed, Hacktoberfest
