Repository bagisto/bagisto, pull requests merged in 2023-04, with the labels that each got.

#7458 Validation message is showing while creating catalog rules
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php
Labels: Getting Fixed, Admin

#7456 issue #7407 fix
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
Labels: Getting Fixed

#7463 issue #7459 fixed
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_dark.scss
Labels: Getting Fixed

#7440 Now not getting exception while trying to create configurable product.
  packages/Webkul/Product/src/Repositories/ProductRepository.php
Labels: Getting Fixed, Approved

#7423 Issue #7420 Resolved
  packages/Webkul/Admin/src/Resources/views/marketing/email-marketing/campaigns/create.blade.php
Labels: Getting Fixed, Approved

#7404 dashboard menu icon issue resolved
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
Labels: Getting Fixed, Approved

#7470 Now we can set street address lines
  packages/Webkul/Admin/src/Resources/views/customers/addresses/create.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/customer-info.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/address/create.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/address/edit.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/create.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/customers/account/address/edit.blade.php
Labels: QA Passed

#7469 issue #7466 fixed
  packages/Webkul/Velocity/src/Resources/assets/js/UI/components/header-mobile.vue
Labels: QA Passed

#7461 issue fixed #7449
  packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/filters/column-filter.vue
Labels: QA Passed

#7399 Drag drop image
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/src/Resources/assets/sass/app.scss
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/images.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/videos.blade.php
  packages/Webkul/Admin/src/Routes/catalog-routes.php
  packages/Webkul/Attribute/src/Http/Controllers/AttributeController.php
  packages/Webkul/Ui/src/Resources/assets/js/components/image/image-item.vue
  packages/Webkul/Ui/src/Resources/assets/sass/app.scss
  packages/Webkul/Velocity/src/Resources/views/admin/catelog/categories/category-icon.blade.php
Labels: QA Passed

#7482 Issue fixed #6723
  packages/Webkul/Ui/src/Http/routes.php
Labels: QA Passed

#7396 Customer calender
  packages/Webkul/Admin/src/Resources/views/customers/create.blade.php
Labels: QA Passed

#7462 shipping imput filed fixed
  packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php
Labels: QA Passed

#7471 Issue #7452 fixed.
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
Labels: QA Passed

#7438 Issue #7329 fixed
  .env.example
  config/services.php
  packages/Webkul/Core/src/Console/Commands/ExchangeRateUpdate.php
  packages/Webkul/Core/src/Helpers/Exchange/ExchangeRates.php
  packages/Webkul/Core/src/Helpers/Exchange/FixerExchange.php
  packages/Webkul/Core/src/Http/Controllers/ExchangeRateController.php
Labels: QA Passed, API

#7303 Fixing #7264 issue
  packages/Webkul/Checkout/src/Cart.php
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-info.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php
Labels: QA Passed

#7349 issue #7136 fixed
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
  packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php
Labels: QA Passed

#7483 Issue #7450 fixed
  packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
Labels: QA Passed

#7465 Issue Fixed #7417
  packages/Webkul/Customer/src/Http/Controllers/WishlistController.php
  packages/Webkul/Customer/src/Models/Wishlist.php
  packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
  packages/Webkul/Velocity/src/Http/Controllers/Shop/ComparisonController.php
  packages/Webkul/Velocity/src/Http/Controllers/Shop/ShopController.php
  packages/Webkul/Velocity/src/Resources/lang/ar/app.php
  packages/Webkul/Velocity/src/Resources/lang/bn/app.php
  packages/Webkul/Velocity/src/Resources/lang/de/app.php
  packages/Webkul/Velocity/src/Resources/lang/en/app.php
  packages/Webkul/Velocity/src/Resources/lang/es/app.php
  packages/Webkul/Velocity/src/Resources/lang/fa/app.php
  packages/Webkul/Velocity/src/Resources/lang/fr/app.php
  packages/Webkul/Velocity/src/Resources/lang/he/app.php
  packages/Webkul/Velocity/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Velocity/src/Resources/lang/it/app.php
  packages/Webkul/Velocity/src/Resources/lang/ja/app.php
  packages/Webkul/Velocity/src/Resources/lang/nl/app.php
  packages/Webkul/Velocity/src/Resources/lang/pl/app.php
  packages/Webkul/Velocity/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Velocity/src/Resources/lang/ru/app.php
  packages/Webkul/Velocity/src/Resources/lang/sin/app.php
  packages/Webkul/Velocity/src/Resources/lang/tr/app.php
  packages/Webkul/Velocity/src/Resources/lang/uk/app.php
  packages/Webkul/Velocity/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php
Labels: QA Passed

#7409 add limit to Velocity advertisement image
  packages/Webkul/Ui/src/Resources/assets/js/components/image/image-wrapper.vue
  packages/Webkul/Velocity/src/Resources/views/admin/meta-info/meta-data.blade.php
Labels: QA Passed

#7490 issue #7419 fixed
  packages/Webkul/Admin/src/DataGrids/CartRuleDataGrid.php
  packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php
Labels: QA Passed

#7380 Issue #7360 fixed
  packages/Webkul/Velocity/src/Resources/views/admin/meta-info/meta-data.blade.php
Labels: QA Passed

#7488 Issue #7476 fixed
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
Labels: QA Passed

#7429 issue #7426 fixed
  packages/Webkul/Admin/src/DataGrids/CartRuleDataGrid.php
Labels: QA Passed

#7503 Default number added #7180
  packages/Webkul/Product/src/Helpers/Toolbar.php
  packages/Webkul/Product/src/Repositories/ProductRepository.php
Labels: QA Passed

#7500 Configurable price changed issue fixed #7216
  packages/Webkul/Product/src/Listeners/Product.php
Labels: QA Passed

#7504 Improvised cms page datagrid #6703
  packages/Webkul/Admin/src/DataGrids/CMSPageDataGrid.php
  packages/Webkul/Ui/src/DataGrid/DataGrid.php
Labels: QA Passed

#7506 File attribute issue fixed #7492
  packages/Webkul/Product/src/Type/AbstractType.php
Labels: In Testing

#7508 Fixed checkout issue
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage/customer-new-form.blade.php
Labels: QA Passed

#7491 issue #7410 fixed
  packages/Webkul/Admin/src/Config/system.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Product/src/Models/Product.php
  packages/Webkul/Shop/src/Http/Controllers/CartController.php
  packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/view/cross-sells.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/view/related-products.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/view/up-sells.blade.php
Labels: QA Passed

#7486 Filter option mobile view
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/js/UI/components/header-mobile.vue
  packages/Webkul/Velocity/src/Resources/assets/js/app.js
  packages/Webkul/Velocity/src/Resources/assets/sass/app.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/master.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/list/toolbar.blade.php
Labels: QA Passed

#7510 Qty validation of group and simple
  packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/bundle-items.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/grouped-products.blade.php
Labels: QA Passed

#7525 URL set params added #7168
  packages/Webkul/Ui/publishable/assets/js/ui.js
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
  packages/Webkul/Ui/src/DataGrid/Traits/ProvideDataGridPlus.php
  packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/datagrid-plus.vue
Labels: QA Passed

#7527 issue #7521 fixed
  packages/Webkul/Velocity/src/Resources/assets/images/Arrow-Down-Light.svg
  packages/Webkul/Velocity/src/Resources/assets/sass/app.scss
Labels: QA Passed

#7528 issue #7520 fixed
  packages/Webkul/Velocity/src/Resources/assets/js/UI/components/mini-cart.vue
Labels: QA Passed

#7530 issue #7518 fixed
  packages/Webkul/Admin/src/DataGrids/CartRuleCouponDataGrid.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
  packages/Webkul/Admin/src/Routes/marketing-routes.php
Labels: In Testing

#7534 Child level and locale level category handled #7517
  packages/Webkul/Category/src/Models/Category.php
  packages/Webkul/Core/src/Eloquent/TranslatableModel.php
  packages/Webkul/Core/src/Helpers/Locales.php
  packages/Webkul/Velocity/src/Http/Controllers/Shop/ShopController.php
  pint.json
Labels: QA Passed

#7533 Fixed locale issue
  packages/Webkul/Product/src/Models/Product.php
  packages/Webkul/Velocity/src/Http/Controllers/Shop/CartController.php
Labels: QA Passed

#7540 Variant issue for flat table and like search for elasticsearch feature
  packages/Webkul/Attribute/src/Repositories/AttributeRepository.php
  packages/Webkul/Product/src/Repositories/ElasticSearchRepository.php
  packages/Webkul/Product/src/Repositories/ProductRepository.php
Labels: In Testing

#7539 issue #7532 fixed
  packages/Webkul/Admin/src/Validations/ConfigurableUniqueSku.php
  packages/Webkul/Product/src/Type/Configurable.php
Labels: QA Passed

#7545 rest api urls removed
  packages/Webkul/Core/src/Http/Controllers/CountryStateController.php
  packages/Webkul/Shop/src/Routes/checkout-routes.php
  packages/Webkul/Shop/src/Routes/store-front-routes.php
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
Labels: QA Passed
