Repository bagisto/bagisto, pull requests merged in 2023-11, with the labels that each got.

#8860 [Fixed: forgot password greeting message param.]
  packages/Webkul/Admin/src/Resources/views/emails/admin/forget-password.blade.php
Labels: QA Passed

#8854 [Updated: view_render_event changes for the admin blades.]
  packages/Webkul/Admin/src/Resources/views/components/layouts/anonymous.blade.php
  packages/Webkul/Admin/src/Resources/views/components/layouts/index.blade.php
Labels: Fix Proposed, Hacktoberfest

#8859 fixed category page status issue
  packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
Labels: QA Passed

#8879 Password Update Mail
  packages/Webkul/Shop/src/Mail/Customer/UpdatePasswordNotification.php
  packages/Webkul/Shop/src/Resources/views/emails/customers/update-password.blade.php
Labels: QA Passed

#8875 Fixed Issue #8874
  packages/Webkul/Shop/src/Mail/Customer/RegistrationNotification.php
  packages/Webkul/Shop/src/Resources/views/emails/customers/email-verification.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/customers/registration.blade.php
Labels: QA Passed

#8869 fixed issue #8866
  packages/Webkul/Admin/src/Resources/views/components/drawer/index.blade.php
Labels: QA Passed

#8881 Fixed #8873 - Cancellation emails are being sent to both the customer…
  packages/Webkul/Admin/src/Mail/Order/CanceledNotification.php
  packages/Webkul/Admin/src/Resources/views/emails/orders/canceled.blade.php
  packages/Webkul/Shop/src/Mail/Order/CanceledNotification.php
Labels: QA Passed

#8871 Fixed 8862
  packages/Webkul/Admin/src/Listeners/Invoice.php
  packages/Webkul/Admin/src/Mail/Order/InvoicedNotification.php
  packages/Webkul/Admin/src/Mail/Order/RefundedNotification.php
  packages/Webkul/Admin/src/Resources/views/emails/orders/invoiced.blade.php
  packages/Webkul/Admin/src/Resources/views/emails/orders/refunded.blade.php
Labels: QA Passed

#8897 FIxed Isuse #8886
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
Labels: QA Passed

#8928 fixed lang issue in compare page
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
Labels: In Testing

#8923 Adding More Translation for GUI Installer
  packages/Webkul/Installer/src/Resources/assets/images/spinner.svg
  packages/Webkul/Installer/src/Resources/lang/ar/app.php
  packages/Webkul/Installer/src/Resources/lang/bn/app.php
  packages/Webkul/Installer/src/Resources/lang/de/app.php
  packages/Webkul/Installer/src/Resources/lang/en/app.php
  packages/Webkul/Installer/src/Resources/lang/es/app.php
  packages/Webkul/Installer/src/Resources/lang/fa/app.php
  packages/Webkul/Installer/src/Resources/lang/fr/app.php
  packages/Webkul/Installer/src/Resources/lang/he/app.php
  packages/Webkul/Installer/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Installer/src/Resources/lang/it/app.php
  packages/Webkul/Installer/src/Resources/lang/ja/app.php
  packages/Webkul/Installer/src/Resources/lang/nl/app.php
  packages/Webkul/Installer/src/Resources/lang/pl/app.php
  packages/Webkul/Installer/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Installer/src/Resources/lang/ru/app.php
  packages/Webkul/Installer/src/Resources/lang/sin/app.php
  packages/Webkul/Installer/src/Resources/lang/tr/app.php
  packages/Webkul/Installer/src/Resources/lang/uk/app.php
  packages/Webkul/Installer/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Installer/src/Resources/views/installer/index.blade.php
Labels: QA Passed

#8941 fixed issue #8940
  packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
Labels: QA Passed

#8960 remove mass-actions from acl.php file
  packages/Webkul/Admin/src/Config/acl.php
  packages/Webkul/Admin/src/DataGrids/CMS/CMSPageDataGrid.php
  packages/Webkul/Admin/src/DataGrids/Catalog/AttributeDataGrid.php
  packages/Webkul/Admin/src/DataGrids/Catalog/CategoryDataGrid.php
  packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php
  packages/Webkul/Admin/src/DataGrids/Customers/CustomerDataGrid.php
  packages/Webkul/Admin/src/DataGrids/Customers/ReviewDataGrid.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/index.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/reviews/index.blade.php
Labels: QA Passed

#8958 fixed issue #8955
  packages/Webkul/Shop/src/Http/Resources/CartItemResource.php
  packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
  packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php
Labels: QA Passed

#8975 Fixed issue #8971
  packages/Webkul/Admin/src/Resources/assets/css/app.css
  packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php
Labels: QA Passed

#8984 Issue #8982 fixed.
  packages/Webkul/Paypal/src/Http/Controllers/StandardController.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
Labels: QA Passed

#8985 Issue #8981 fixed.
  packages/Webkul/Admin/src/Helpers/Reporting/Sale.php
Labels: QA Passed, Fix Proposed

#8989 Issue #8986 fixed.
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php
Labels: QA Passed

#9000 Fixed Issue #8934
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php
Labels: QA Passed

#8990 Issue #8931 fixed.
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/billing.blade.php
Labels: QA Passed

#8987 Issue #8852 fixed.
  packages/Webkul/Shop/src/Http/Resources/ProductReviewResource.php
  packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
Labels: QA Passed, Fix Proposed

#8983 Issue #8927 fixed.
  packages/Webkul/Admin/src/Http/Controllers/Sales/InvoiceController.php
  packages/Webkul/Admin/src/Mail/Order/InvoicedNotification.php
  packages/Webkul/Shop/src/Mail/Order/InvoicedNotification.php
Labels: QA Passed

#8959 Fixed Issue #8945
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
  packages/Webkul/Rule/src/Helpers/Validator.php
Labels: QA Passed

#8996 Issue #8980 fixed.
  packages/Webkul/Admin/src/Http/Controllers/Customers/CustomerController.php
  packages/Webkul/Admin/src/Mail/Customer/NewCustomerNotification.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/views/emails/customers/new-customer.blade.php
Labels: QA Passed

#8974 fixed issue #8970
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
Labels: Change Request

#9011 fixed issue #9008
  packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
Labels: QA Passed

#9009 fixed issue #9007
  packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
Labels: QA Passed

#8992 Issue #8689 fixed.
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/static-content.blade.php
Labels: QA Passed

#9012 Issue #8932 fixed.
  app/Http/Kernel.php
  packages/Webkul/Admin/src/Http/Controllers/Settings/ChannelController.php
  packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php
  packages/Webkul/Shop/src/Resources/views/errors/index.blade.php
  public/themes/shop/default/build/assets/app-95486b63.js
  public/themes/shop/default/build/assets/app-9c4ac3be.js
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9015 Fix Attribute colour swatch Issue
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
Labels: QA Passed

#9023 Fixed attribute family edit page general accordion issue
  packages/Webkul/Admin/src/Resources/views/catalog/families/create.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/families/edit.blade.php
  public/themes/admin/default/build/assets/app-73ef8e9b.js
  public/themes/admin/default/build/assets/app-d30d02f6.js
  public/themes/admin/default/build/manifest.json
Labels: QA Passed

#9024 fixed issue #9021
  packages/Webkul/Admin/src/Config/system.php
Labels: QA Passed

#9026 Fixed issue #9022
  packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
  public/themes/shop/default/build/assets/app-9c4ac3be.js
  public/themes/shop/default/build/assets/app-c69da5fc.js
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9028 Fixed issue #9020
  packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/components/seo/index.blade.php
  packages/Webkul/Installer/src/Database/Seeders/Shop/ThemeCustomizationTableSeeder.php
Labels: QA Passed

#9034 fixed issue #9030
  packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
Labels: QA Passed

#9035 Fixed issue #9031
  packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
Labels: QA Passed

#8872 fixed issue #8868
  packages/Webkul/Shop/src/Http/Requests/Customer/AddressRequest.php
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/billing.blade.php
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/shipping.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/addresses/create.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/addresses/edit.blade.php
Labels: QA Passed

#9038 Added validation language in all locale in core package
  packages/Webkul/Core/src/Resources/lang/ar/app.php
  packages/Webkul/Core/src/Resources/lang/ar/validation.php
  packages/Webkul/Core/src/Resources/lang/de/app.php
  packages/Webkul/Core/src/Resources/lang/de/validation.php
  packages/Webkul/Core/src/Resources/lang/fr/app.php
  packages/Webkul/Core/src/Resources/lang/fr/validation.php
  packages/Webkul/Core/src/Resources/lang/he/app.php
  packages/Webkul/Core/src/Resources/lang/he/validation.php
  packages/Webkul/Core/src/Resources/lang/ja/app.php
  packages/Webkul/Core/src/Resources/lang/ja/validation.php
  packages/Webkul/Core/src/Resources/lang/nl/app.php
  packages/Webkul/Core/src/Resources/lang/nl/validation.php
  packages/Webkul/Core/src/Resources/lang/pl/app.php
  packages/Webkul/Core/src/Resources/lang/pl/validation.php
  packages/Webkul/Core/src/Resources/lang/ru/app.php
  packages/Webkul/Core/src/Resources/lang/ru/validation.php
  packages/Webkul/Core/src/Resources/lang/sin/app.php
  packages/Webkul/Core/src/Resources/lang/sin/validation.php
  packages/Webkul/Core/src/Resources/lang/uk/app.php
  packages/Webkul/Core/src/Resources/lang/uk/validation.php
Labels: QA Passed

#9052 Removed unused comment.
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php
  packages/Webkul/Shop/src/Resources/views/home/index.blade.php
Labels: QA Passed

#9037 Fixed issue #9032
  packages/Webkul/Shop/src/Http/Controllers/Customer/RegistrationController.php
  packages/Webkul/Shop/src/Resources/views/customers/account/profile/edit.blade.php
Labels: QA Passed

#9047 Added back button in configuration to redirect in index page.
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/configuration/edit.blade.php
Labels: QA Passed

#9050 Fixed street address validation for arebic language
  packages/Webkul/Core/src/Rules/Address.php
  packages/Webkul/Shop/src/Resources/assets/js/app.js
  public/themes/shop/default/build/assets/app-8b8c182d.js
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9051 Shop image search fixed.
  packages/Webkul/Shop/src/Data/postal-code.json
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php
  packages/Webkul/Shop/src/Resources/views/search/images/index.blade.php
Labels: QA Passed

#9053 Issue #8921 fixed.
  packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
Labels: QA Passed

#9041 Added Pagination on customer orders Page
  packages/Webkul/Admin/src/Config/acl.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php
  packages/Webkul/Admin/src/Routes/customers-routes.php
  packages/Webkul/Shop/src/Http/Resources/ProductReviewResource.php
Labels: QA Passed

#9056 Issue #9005 fixed.
  packages/Webkul/Admin/src/Providers/AdminServiceProvider.php
  packages/Webkul/Core/src/Tree.php
Labels: In Testing

#9054 Fixed issue #9049
  packages/Webkul/Admin/src/Resources/lang/it/app.php
Labels: QA Passed

#9058 Fixed theme creation issue.
  packages/Webkul/Theme/src/Models/ThemeCustomization.php
Labels: QA Passed

#9065 Issue #9064 fixed.
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php
Labels: QA Passed, Fix Proposed

#9044 Footer link theme updation issue fix.
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/category-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/footer-links.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/image-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/product-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/services-content.blade.php
Labels: QA Passed, Fix Proposed
