Repository bagisto/bagisto, pull requests merged in 2023-03, with the labels that each got.

#7334 Triggers Removed
  .github/workflows/ci.yml
  composer.json
  database/migrations/2019_11_21_194541_add_column_url_path_to_category_translations.php
  database/migrations/2019_11_21_194608_add_stored_function_to_get_url_path_of_category.php
  database/migrations/2019_11_21_194627_add_trigger_to_category_translations.php
  database/migrations/2019_11_21_194648_add_url_path_to_existing_category_translations.php
  database/migrations/2019_11_21_194703_add_trigger_to_categories.php
  database/migrations/2020_01_06_173505_alter_trigger_category_translations.php
  database/migrations/2020_01_06_173524_alter_stored_function_url_path_category.php
  database/migrations/2020_01_06_195305_alter_trigger_on_categories.php
  packages/Webkul/Category/src/Listeners/Category.php
  packages/Webkul/Category/src/Models/Category.php
  packages/Webkul/Category/src/Providers/CategoryServiceProvider.php
  packages/Webkul/Category/src/Providers/EventServiceProvider.php
  packages/Webkul/Shop/src/Database/Migrations/2019_11_21_194541_add_column_url_path_to_category_translations.php
  packages/Webkul/Shop/src/Database/Migrations/2019_11_21_194608_add_stored_function_to_get_url_path_of_category.php
  packages/Webkul/Shop/src/Database/Migrations/2019_11_21_194627_add_trigger_to_category_translations.php
  packages/Webkul/Shop/src/Database/Migrations/2019_11_21_194648_add_url_path_to_existing_category_translations.php
  packages/Webkul/Shop/src/Database/Migrations/2019_11_21_194703_add_trigger_to_categories.php
  packages/Webkul/Shop/src/Database/Migrations/2020_01_06_173505_alter_trigger_category_translations.php
  packages/Webkul/Shop/src/Database/Migrations/2020_01_06_173524_alter_stored_function_url_path_category.php
  packages/Webkul/Shop/src/Database/Migrations/2020_01_06_195305_alter_trigger_on_categories.php
  packages/Webkul/Shop/src/Database/Migrations/2023_03_02_193725_remove_functions_and_trigger.php
  tests/_support/Helper/Trigger.php
  tests/_support/TriggerTester.php
  tests/trigger.suite.yml
  tests/trigger/Shop/DatabaseLogicCest.php
  tests/trigger/Shop/TriggerCest.php
  tests/unit/Category/CategoryCest.php
Labels: Getting Fixed

#7347 Status filter ui fixed
  packages/Webkul/Ui/publishable/assets/js/ui.js
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
  packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/filters/column-filter.vue
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/datagrid.scss
Labels: Getting Fixed

#7348 Added image cache file
  config/.gitignore
  config/imagecache.php
Labels: In Testing

#7350 Elastic search bug fixed
  packages/Webkul/Product/src/Repositories/ElasticSearchRepository.php
Labels: Getting Fixed, Critical

#7345 Change load routes in Packages
  packages/Webkul/Admin/src/Providers/AdminServiceProvider.php
  packages/Webkul/Admin/src/Routes/auth-routes.php
  packages/Webkul/Admin/src/Routes/catalog-routes.php
  packages/Webkul/Admin/src/Routes/cms-routes.php
  packages/Webkul/Admin/src/Routes/configuration-routes.php
  packages/Webkul/Admin/src/Routes/customers-routes.php
  packages/Webkul/Admin/src/Routes/marketing-routes.php
  packages/Webkul/Admin/src/Routes/notification-routes.php
  packages/Webkul/Admin/src/Routes/rest-routes.php
  packages/Webkul/Admin/src/Routes/sales-routes.php
  packages/Webkul/Admin/src/Routes/settings-routes.php
  packages/Webkul/Shop/src/Providers/ShopServiceProvider.php
  packages/Webkul/Shop/src/Routes/checkout-routes.php
  packages/Webkul/Shop/src/Routes/customer-routes.php
  packages/Webkul/Shop/src/Routes/store-front-routes.php
  packages/Webkul/Velocity/src/Providers/VelocityServiceProvider.php
  packages/Webkul/Velocity/src/Routes/admin-routes.php
  packages/Webkul/Velocity/src/Routes/front-routes.php
Labels: In Testing

#7325 Issue #7200 fixed
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
Labels: Change Request

#7343 Notification ui issue fixed
  config/db-blade-compiler.php
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/publishable/assets/js/ui.js
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
  packages/Webkul/Ui/src/Resources/assets/sass/app.scss
Labels: Getting Fixed, Critical

#7312 Added advertisement classes and enhanced images
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/publishable/assets/js/admin.js.LICENSE.txt
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/home.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
  packages/Webkul/Velocity/src/Resources/views/shop/home/advertisements/advertisement-four.blade.php
Labels: Getting Fixed

#7367 Velocity Page Fixed CSS #7363
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
Labels: Getting Fixed

#7365 Issue #7364 fixed
  packages/Webkul/Velocity/src/Resources/lang/en/app.php
  packages/Webkul/Velocity/src/Resources/lang/it/app.php
  packages/Webkul/Velocity/src/Resources/lang/pt_BR/app.php
Labels: Getting Fixed

#7252 Arabic Validation issue #7181
  packages/Webkul/Core/src/Contracts/Validations/Address.php
  packages/Webkul/Core/src/Contracts/Validations/AlphaNumericSpace.php
Labels: Getting Fixed

#7391 Shop front footer ui issue fixed #7355
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/js/jquery-ez-plus.js
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/components/footer.scss
Labels: Getting Fixed

#7175 Refund issue #7170
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php
  packages/Webkul/Product/src/Listeners/Refund.php
  packages/Webkul/Sales/src/Repositories/RefundRepository.php
Labels: Critical, Change Request

#7393 issue #7371 fixed
  packages/Webkul/Admin/src/Resources/views/catalog/families/create.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/families/edit.blade.php
  packages/Webkul/Ui/src/Resources/assets/sass/app.scss
Labels: Getting Fixed

#7386 Issue Fixed #7358 in dark mode
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_dark.scss
Labels: Getting Fixed

#7385 Issue #7383 occurred with elastic search fixed
  packages/Webkul/Product/src/Repositories/ElasticSearchRepository.php
  packages/Webkul/Product/src/Repositories/ProductRepository.php
Labels: Getting Fixed

#7421 Issue fixed in calender overlaping ui
  packages/Webkul/BookingProduct/src/Resources/views/admin/sales/bookings/index.blade.php
Labels: Getting Fixed

#7414 fixed issue #7407
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Product/src/Http/Controllers/ReviewController.php
Labels: Getting Fixed

#7405 Fixed Search Issues
  packages/Webkul/Product/src/Repositories/ElasticSearchRepository.php
Labels: Getting Fixed

#7425 #7332 issue fixed
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/particals/header-compts.blade.php
Labels: Getting Fixed

#7379 Booking product
  packages/Webkul/Velocity/src/Resources/views/shop/products/add-to-cart.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/buy-now.blade.php
Labels: Getting Fixed

#7333 Sub Category issues
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/js/jquery-ez-plus.js
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/js/UI/components/sidebar.vue
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/master.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/index.blade.php
Labels: Getting Fixed
