Repository bagisto/bagisto, pull requests merged in 2023-02, with the labels that each got.

#7197 Flash message issue fixed
  packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerController.php
  packages/Webkul/Admin/src/Http/Controllers/Customer/CustomerGroupController.php
  packages/Webkul/Admin/src/Http/Controllers/Sales/InvoiceController.php
  packages/Webkul/Admin/src/Http/Controllers/Sales/OrderController.php
  packages/Webkul/Admin/src/Http/Controllers/Sales/RefundController.php
  packages/Webkul/Admin/src/Http/Controllers/Sales/ShipmentController.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
Labels: Getting Fixed

#7215 Issue fixed #7161
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/particals/header-compts.blade.php
Labels: Getting Fixed

#7226 issue #7217 fixed
  packages/Webkul/Ui/src/Resources/assets/sass/app.scss
Labels: Getting Fixed

#7247 issue #7235
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
Labels: Getting Fixed

#7246 Issue #7244 resolved
  packages/Webkul/Shop/src/Resources/views/products/list/layered-navigation.blade.php
Labels: Getting Fixed

#7287 Removed DB Blade Compiler #7067
  composer.json
  composer.lock
  config/app.php
  packages/Webkul/Core/src/Console/Commands/BagistoPublish.php
  packages/Webkul/Core/src/Database/Seeders/ChannelTableSeeder.php
  packages/Webkul/Shop/src/Resources/views/cms/page.blade.php
  packages/Webkul/Shop/src/Resources/views/home/index.blade.php
  packages/Webkul/Shop/src/Resources/views/layouts/footer/footer.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/cms/page.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/home/index.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/footer/footer-links/footer-middle.blade.php
Labels: Getting Fixed, Critical

#7248 Fixed issue #7227
  packages/Webkul/Customer/src/Http/Controllers/ResetPasswordController.php
Labels: Getting Fixed

#7268 fixed invoice issue
  packages/Webkul/Admin/src/Resources/views/sales/address.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
Labels: Getting Fixed

#7289 Category localewise
  packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
  packages/Webkul/Velocity/src/Resources/assets/sass/app.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss
Labels: Getting Fixed

#7275 UI-filter Fixed
  packages/Webkul/Velocity/src/Resources/assets/sass/app.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
  packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss
Labels: Getting Fixed

#7292 Issue #7283 fixed
  packages/Webkul/Core/src/Core.php
Labels: Getting Fixed, Critical

#7253 Fixed issue #7177
  packages/Webkul/Admin/src/Resources/views/catalog/products/field-types/datetime.blade.php
Labels: Getting Fixed

#6811 Fixed issue #6743
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Http/Controllers/Shop/ShopController.php
  packages/Webkul/Velocity/src/Resources/assets/js/UI/components/sidebar.vue
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
Labels: Getting Fixed, Hacktoberfest

#7293 changed the mass action ui
  packages/Webkul/Product/src/Http/Controllers/ProductController.php
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/publishable/assets/js/ui.js
  packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/datagrid-plus.vue
  packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/partials/datagrid-filter-tags.vue
  packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/partials/datagrid-table.vue
  packages/Webkul/Ui/src/Resources/assets/sass/includes/components.scss
Labels: Getting Fixed

#7294 Issue #7286 Fixed
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
Labels: Getting Fixed

#7304 Change the checkbox in dark mode
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/images/Checkbox-Checked.svg
  packages/Webkul/Admin/publishable/assets/images/checked-checkbox.png
  packages/Webkul/Admin/src/Resources/assets/images/Checkbox-Checked.svg
  packages/Webkul/Admin/src/Resources/assets/images/checked-checkbox.png
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_dark.scss
Labels: Getting Fixed

#7298 ui package recompile
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/publishable/assets/js/ui.js
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
Labels: Getting Fixed

#7192 Only natural number checking
  packages/Webkul/Core/src/Contracts/Validations/CommaSeparatedInteger.php
Labels: In Testing

#7311 Category banner
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
  packages/Webkul/Category/src/Database/Migrations/2023_01_16_163456_add_category_banner_to_categories_table.php
  packages/Webkul/Category/src/Models/Category.php
  packages/Webkul/Category/src/Repositories/CategoryRepository.php
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/publishable/assets/js/ui.js
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
  packages/Webkul/Ui/publishable_back/assets/css/ui.css
  packages/Webkul/Ui/publishable_back/assets/js/ui.js
  packages/Webkul/Ui/publishable_back/assets/mix-manifest.json
  packages/Webkul/Ui/src/Resources/assets/js/app.js
  packages/Webkul/Ui/src/Resources/assets/js/components/image/large-image-wrapper.vue
  packages/Webkul/Ui/src/Resources/assets/sass/app.scss
  packages/Webkul/Velocity/src/Resources/views/shop/products/index.blade.php
Labels: Getting Fixed

#7300 Shippingmethod
  packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
Labels: Getting Fixed

#7280 Product list mobile
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/components.js.LICENSE.txt
  packages/Webkul/Velocity/publishable/assets/js/velocity-core.js
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/js/app-core.js
Labels: Getting Fixed

#7259 issue #7201
  packages/Webkul/Product/src/Type/Configurable.php
Labels: Getting Fixed

#7316 Issue #7314 fixed.
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/js/UI/components/product-card.vue
Labels: Getting Fixed

#7274 Sub Category on Category Page
  packages/Webkul/Category/src/Repositories/CategoryRepository.php
  packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
  packages/Webkul/Velocity/src/Resources/views/shop/products/index.blade.php
Labels: Getting Fixed

#7179 Issue #6972 Fixed
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/header/index.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/layouts/particals/header-compts.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/wishlist.blade.php
Labels: Getting Fixed

#7251 Fixed issue #7189
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/src/Resources/assets/js/UI/components/sidebar.vue
  packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
Labels: Getting Fixed

#7193 Admin Profile Issue Resolved
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/publishable/assets/js/admin.js
  packages/Webkul/Admin/publishable/assets/js/admin.js.LICENSE.txt
  packages/Webkul/Admin/publishable/assets/mix-manifest.json
  packages/Webkul/Admin/src/Resources/assets/js/components/darkmode/dark.vue
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
  packages/Webkul/Admin/src/Resources/views/layouts/nav-top.blade.php
  packages/Webkul/Ui/publishable/assets/css/ui.css
  packages/Webkul/Ui/publishable/assets/js/ui.js
  packages/Webkul/Ui/publishable/assets/mix-manifest.json
  packages/Webkul/Ui/src/Resources/assets/sass/app.scss
Labels: Getting Fixed

#7317 Added Hot Fix For Shipment #7281
  packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php
Labels: Getting Fixed

#7315 wishlist text removed
  packages/Webkul/Velocity/src/Resources/views/shop/products/add-to-cart.blade.php
  packages/Webkul/Velocity/src/Resources/views/shop/products/wishlist.blade.php
Labels: Getting Fixed

#6974 Array_merge() speed up
  packages/Webkul/Attribute/src/Repositories/AttributeRepository.php
  packages/Webkul/BookingProduct/src/Http/Controllers/Shop/BookingProductController.php
  packages/Webkul/BookingProduct/src/Type/Booking.php
  packages/Webkul/Product/src/Type/Bundle.php
  packages/Webkul/Product/src/Type/Grouped.php
  packages/Webkul/Shipping/src/Shipping.php
  public/installer/AdminConfig.php
Labels: In Testing

#7266 Issue #7171 fixed
  packages/Webkul/Admin/publishable/assets/css/admin.css
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_dashboard.scss
  packages/Webkul/Admin/src/Resources/assets/sass/partials/_default.scss
Labels: Getting Fixed

#7327 Issue #6353 fixed.
  packages/Webkul/Velocity/publishable/assets/css/velocity.css
  packages/Webkul/Velocity/publishable/assets/js/components.js
  packages/Webkul/Velocity/publishable/assets/js/velocity.js
  packages/Webkul/Velocity/publishable/assets/mix-manifest.json
  packages/Webkul/Velocity/src/Resources/assets/sass/app.scss
  packages/Webkul/Velocity/src/Resources/views/shop/guest/compare/compare-products.blade.php
Labels: Getting Fixed

#7323 wishlist-ui-issue-code-optimize
  packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss
Labels: Getting Fixed
