Repository bagisto/bagisto, pull requests merged in 2023-12, with the labels that each got.

#9042 Fix checkout page address show billing address selected while create …
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/index.blade.php
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/shipping.blade.php
Labels: QA Passed

#8994 dark mode input box dark mode fixed.
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
Labels: QA Passed, Fix Proposed

#9063 Tinymce issue image upload image fixed.
  packages/Webkul/Admin/src/Resources/views/components/tinymce/index.blade.php
Labels: Fix Proposed

#9016 Add league fractal dependency. #8991
  composer.json
  composer.lock
Labels: Fix Proposed, Conflicts

#9069 Downloadable issue fix in shop
  packages/Webkul/Shop/src/Http/Controllers/Customer/Account/DownloadableProductController.php
Labels: QA Passed

#9027 Fixed shop customer order data-grid
  packages/Webkul/Admin/src/DataGrids/Marketing/Communications/CampaignDataGrid.php
  packages/Webkul/Admin/src/Resources/views/components/example.blade.php
  packages/Webkul/Shop/src/DataGrids/OrderDataGrid.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/views/components/example.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
Labels: QA Passed

#9074 Fix Notification UI and page redirection
  packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
  packages/Webkul/Admin/src/Resources/views/notifications/index.blade.php
Labels: QA Passed

#9078 Fixed Issue #9076
  packages/Webkul/Admin/src/Resources/views/components/datagrid/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/inventory-sources/edit.blade.php
Labels: QA Passed

#9084 Issue #8687 fixed.
  packages/Webkul/Shop/src/Resources/views/components/media/index.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
Labels: QA Passed

#9088 remove duplicate event
  packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php
Labels: QA Passed

#9121 fixed file upload input field for dark theme in product page
  packages/Webkul/Admin/src/Resources/views/catalog/products/edit/controls.blade.php
Labels: QA Passed

#9098 Fixed issue #9096
  packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
Labels: QA Passed

#9097 Issue #9093 fixed.
  packages/Webkul/Admin/src/Config/system.php
  packages/Webkul/Admin/src/Http/Controllers/ConfigurationController.php
  packages/Webkul/Admin/src/Http/Requests/ConfigurationForm.php
Labels: QA Passed

#9131 Fix Category Page Checkbox issue
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
  public/themes/admin/default/build/assets/app-d20fdcc6.css
  public/themes/admin/default/build/assets/app-d6e62d71.js
Labels: QA Passed

#8915 Admin is not receiving mail for customer registration, after enabling the feature from Notifications in Configure Section - 8893
  packages/Webkul/Admin/src/Listeners/Customer.php
  packages/Webkul/Admin/src/Mail/Customer/RegistrationNotification.php
  packages/Webkul/Admin/src/Providers/EventServiceProvider.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/emails/customers/registration.blade.php
Labels: QA Passed

#9139 Issue #9135 fixed.
  packages/Webkul/Admin/src/Resources/views/catalog/products/edit/links.blade.php
Labels: QA Passed

#9147 Checkout page issue for guest.
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/billing.blade.php
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/index.blade.php
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/addresses/shipping.blade.php
Labels: Conflicts

#9185 Added confirmation modal in wish-list in delete all
  packages/Webkul/Admin/src/Resources/assets/css/app.css
  packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php
  public/themes/shop/default/build/assets/app-1b4decc3.css
  public/themes/shop/default/build/assets/app-348beba2.js
  public/themes/shop/default/build/assets/app-3c12b944.js
  public/themes/shop/default/build/assets/app-5bd7b44f.css
  public/themes/shop/default/build/manifest.json
Labels: In Testing

#9193 fixed issue #9192
  packages/Webkul/Admin/src/Resources/views/customers/groups/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/communications/events/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/communications/subscribers/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/search-seo/search-synonyms/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/search-seo/search-terms/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/search-seo/sitemaps/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/search-seo/url-rewrites/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/currencies/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/exchange-rates/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/locales/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/taxes/categories/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php
Labels: QA Passed, Fix Proposed, Change Request

#9184 Fixed: #9181
  packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
Labels: QA Passed

#9190 fixed issue #9189
  packages/Webkul/Admin/src/Resources/views/dashboard/todays-details.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/images.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/index.blade.php
Labels: QA Passed, Fix Proposed, Change Request

#9204 Fixed issue #9194
  packages/Webkul/Admin/src/Http/Controllers/Settings/UserController.php
Labels: QA Passed, Fix Proposed

#9202 Fixed shipment console error and data-grid delete icon condition
  packages/Webkul/Admin/src/Resources/views/customers/groups/index.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/reviews/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/communications/events/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/communications/subscribers/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/search-seo/search-synonyms/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/search-seo/search-terms/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/search-seo/sitemaps/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/search-seo/url-rewrites/index.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/currencies/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/exchange-rates/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/locales/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/taxes/categories/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php
  packages/Webkul/DataGrid/src/Action.php
  packages/Webkul/DataGrid/src/DataGrid.php
Labels: QA Passed

#9206 Added tax-rate export feature
  packages/Webkul/Admin/src/Resources/views/components/datagrid/export/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/taxes/rates/index.blade.php
Labels: QA Passed

#9212 fixed product mass update issue
  packages/Webkul/Marketing/src/Listeners/Product.php
Labels: QA Passed

#9198 Issue Fixes in attribute page
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/components/table/thead/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/table/thead/tr.blade.php
  public/themes/admin/default/build/assets/app-28130295.css
  public/themes/admin/default/build/assets/app-460306e8.js
  public/themes/admin/default/build/assets/app-849544a8.js
  public/themes/admin/default/build/manifest.json
Labels: QA Passed
