Repository bagisto/bagisto, pull requests merged in 2023-10, with the labels that each got.

#8582 Fixed #8571 (Required Sign Asterisk)
  packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
Labels: QA Passed

#8632 Fixed translation issue #8631
  packages/Webkul/Product/src/Type/Downloadable.php
Labels: QA Passed

#8634 fixed issue #8630
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php
Labels: QA Passed

#8638 Fixed Translation issue
  packages/Webkul/Admin/src/Http/Controllers/Catalog/CategoryController.php
Labels: QA Passed

#8644 fixed issue #8643
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/components/table/thead/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/table/thead/tr.blade.php
Labels: QA Passed

#8646 fixed root category delete message issue
  packages/Webkul/Admin/src/Http/Controllers/Catalog/CategoryController.php
Labels: QA Passed

#8667 fixed issue #8666
  packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar.blade.php
Labels: QA Passed

#8661 fixed issue #8652
  packages/Webkul/Shop/src/Resources/views/customers/account/addresses/index.blade.php
Labels: QA Passed

#8657 Fixed Space Issue in option
  packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
Labels: QA Passed

#8642 Add VAT ID translation
  packages/Webkul/Customer/src/Captcha.php
  packages/Webkul/Customer/src/Resources/lang/ar/app.php
  packages/Webkul/Customer/src/Resources/lang/bn/app.php
  packages/Webkul/Customer/src/Resources/lang/de/app.php
  packages/Webkul/Customer/src/Resources/lang/en/app.php
  packages/Webkul/Customer/src/Resources/lang/es/app.php
  packages/Webkul/Customer/src/Resources/lang/fa/app.php
  packages/Webkul/Customer/src/Resources/lang/fr/app.php
  packages/Webkul/Customer/src/Resources/lang/he/app.php
  packages/Webkul/Customer/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Customer/src/Resources/lang/it/app.php
  packages/Webkul/Customer/src/Resources/lang/ja/app.php
  packages/Webkul/Customer/src/Resources/lang/nl/app.php
  packages/Webkul/Customer/src/Resources/lang/pl/app.php
  packages/Webkul/Customer/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Customer/src/Resources/lang/ru/app.php
  packages/Webkul/Customer/src/Resources/lang/sin/app.php
  packages/Webkul/Customer/src/Resources/lang/tr/app.php
  packages/Webkul/Customer/src/Resources/lang/uk/app.php
  packages/Webkul/Customer/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Customer/src/Rules/VatIdRule.php
Labels: QA Passed

#8639 Fixed #8635
  packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php
Labels: QA Passed

#8628 Fixed #8623
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/views/customers/forgot-password.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/reset-password.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php
Labels: QA Passed

#8608 Fixed #8603 - Resolved SQL exception and fixed translation-related is…
  packages/Webkul/Shop/src/Http/Controllers/Customer/Account/OrderController.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/views/customers/account/orders/pdf.blade.php
Labels: QA Passed

#8662 fixed issue #8659
  packages/Webkul/Core/src/Core.php
  packages/Webkul/Product/src/Type/AbstractType.php
Labels: QA Passed

#8669 fixed issue #8651 and added shimmer for review section
  packages/Webkul/Shop/src/Resources/views/components/shimmer/customers/account/reviews/index.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/reviews/index.blade.php
  public/themes/shop/default/build/assets/app-acd3d8d3.css
  public/themes/shop/default/build/assets/app-fbd85523.css
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#8665 fixed issue #8663
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
Labels: QA Passed

#8647 fixed id not visible and redirection issue in customer view
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php
Labels: QA Passed

#8670 Fixed #8660 (Calender Icon Compatible with Multiple Browsers)
  packages/Webkul/Admin/src/Resources/views/components/flat-picker/date.blade.php
  packages/Webkul/Admin/src/Resources/views/components/flat-picker/datetime.blade.php
Labels: QA Passed

#8676 fixed issue #8675
  packages/Webkul/Admin/src/Resources/views/configuration/dependent-field-type.blade.php
Labels: QA Passed

#8680 Fix Attribute page options Scroll Issue
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
Labels: QA Passed

#8650 fixed issue #8648
  packages/Webkul/Shop/src/DataGrids/OrderDataGrid.php
Labels: QA Passed

#8653 fixed issue #8649
  packages/Webkul/Shop/src/Http/Controllers/API/AddressController.php
  packages/Webkul/Shop/src/Http/Controllers/Customer/Account/AddressController.php
Labels: QA Passed

#8708 Fixed Issue #8705
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
Labels: QA Passed

#8684 Fixed #8683
  packages/Webkul/Customer/src/Repositories/CustomerAddressRepository.php
Labels: QA Passed

#8679 fixed review button configuration issue
  packages/Webkul/Admin/src/Resources/views/components/media/images.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
Labels: QA Passed

#8702 Fixed - #8700
  packages/Webkul/Sales/src/Generators/Sequencer.php
  packages/Webkul/Shop/src/Resources/views/customers/account/orders/view.blade.php
Labels: QA Passed

#8692 Fixed Issue #8691
  packages/Webkul/Admin/src/Resources/views/sales/orders/images.blade.php
Labels: QA Passed

#8707 fixed issue #8701
  packages/Webkul/Shop/src/Resources/views/checkout/success.blade.php
Labels: QA Passed

#8720 All Lang Added For Reporting Section
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
Labels: QA Passed

#8710 Fixed Issue #8697
  packages/Webkul/Shop/src/Mail/Customer/RegistrationNotification.php
  packages/Webkul/Shop/src/Mail/Customer/SubscriptionNotification.php
  packages/Webkul/Shop/src/Mail/Customer/UpdatePasswordNotification.php
  packages/Webkul/Shop/src/Resources/views/emails/customers/registration.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/customers/subscribed.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/customers/update-password.blade.php
Labels: QA Passed

#8744 [Fixed: #8743]
  packages/Webkul/Admin/src/Helpers/Reporting.php
  packages/Webkul/Admin/src/Helpers/Reporting/Sale.php
Labels: QA Passed

#8763 Fixed Issue #8444
  packages/Webkul/Admin/src/Resources/views/components/media/images.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/index.blade.php
Labels: QA Passed

#8778 Fixed Issue #8776
  packages/Webkul/Admin/src/Resources/views/components/shimmer/reporting/sales/purchase-funnel.blade.php
Labels: QA Passed

#8780 Fixed Issue #8779
  packages/Webkul/Shop/src/Resources/views/customers/sign-in.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php
  packages/Webkul/SocialLogin/src/Providers/EventServiceProvider.php
Labels: QA Passed

#8782 change product setting icon
  packages/Webkul/Admin/src/Config/system.php
  packages/Webkul/Admin/src/Resources/assets/images/settings/product.svg
  public/themes/admin/default/build/assets/product-357134fb.svg
  public/themes/admin/default/build/manifest.json
Labels: QA Passed

#8772 Fixed Issue #8733
  packages/Webkul/Admin/src/Helpers/Reporting.php
Labels: QA Passed

#8781 Fixed Issue #8777
  packages/Webkul/Admin/src/Resources/views/components/shimmer/reporting/sales/total-refunds.blade.php
Labels: QA Passed

#8810 [Fixed: #8809]
  packages/Webkul/Admin/src/Http/Controllers/Catalog/AttributeController.php
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
Labels: In Testing

#8814 [Fixed: Attribute's option sort issue for the configurable product.]
  packages/Webkul/Product/src/Helpers/ConfigurableOption.php
Labels: Bug, QA Passed, Fix Proposed, Hacktoberfest

#8796 Reset Coupon Form on Shop Package
  packages/Webkul/Shop/src/Resources/views/checkout/cart/coupon.blade.php
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/coupon.blade.php
Labels: QA Passed

#8788 Re Stored Product Copy Feature
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/edit/categories.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/edit/inventories.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/edit/links.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/index.blade.php
  packages/Webkul/Product/src/Repositories/ProductRepository.php
  packages/Webkul/Product/src/Type/AbstractType.php
Labels: QA Passed

#8827 Fixed Issue #8516
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
Labels: QA Passed

#8839 Fixed Issue #8835
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
Labels: QA Passed

#8795 Fixed status label class issue
  packages/Webkul/Admin/src/DataGrids/Customers/ReviewDataGrid.php
  packages/Webkul/Admin/src/DataGrids/Sales/OrderDataGrid.php
  packages/Webkul/Admin/src/Resources/assets/css/app.css
  packages/Webkul/Admin/src/Resources/views/components/datagrid/filters.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/index.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php
  packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
  packages/Webkul/Admin/src/Resources/views/reporting/customers/index.blade.php
  packages/Webkul/Admin/src/Resources/views/reporting/products/index.blade.php
  packages/Webkul/Admin/src/Resources/views/reporting/sales/index.blade.php
  packages/Webkul/Admin/src/Resources/views/reporting/view.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
  public/themes/admin/default/build/assets/app-120879da.css
Labels: QA Passed

#8813 Update Newsletter Configuration As True
  packages/Webkul/Admin/src/Config/system.php
  packages/Webkul/Shop/src/Resources/views/components/flash-group/index.blade.php
  public/themes/shop/default/build/assets/app-15058efa.css
  public/themes/shop/default/build/assets/app-aa4b60e6.js
Labels: QA Passed

#8819 Fixed Issue #8816
  packages/Webkul/Shop/src/Resources/views/components/flash-group/index.blade.php
  public/themes/shop/default/build/assets/app-15058efa.css
  public/themes/shop/default/build/assets/app-aa4b60e6.js
Labels: QA Passed

#8834 Fixed Issue #8826
  packages/Webkul/Shop/src/Resources/assets/images/spinner.svg
  packages/Webkul/Shop/src/Resources/views/categories/view.blade.php
  packages/Webkul/Tax/src/Helpers/Tax.php
  public/themes/shop/default/build/assets/app-1b955b16.css
  public/themes/shop/default/build/assets/app-277021bf.css
  public/themes/shop/default/build/assets/app-c6e74274.js
  public/themes/shop/default/build/assets/spinner-51c5cf50.svg
  public/themes/shop/default/build/manifest.json
Labels: QA Passed
