Repository bagisto/bagisto, pull requests merged in 2024-03, with the labels that each got.

#9556 Fixed issue #9551
  packages/Webkul/Admin/src/DataGrids/Sales/OrderTransactionsDataGrid.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
Labels: QA Passed

#9574 Fixed issue #9567
  packages/Webkul/Shop/src/Resources/views/components/datagrid/index.blade.php
  packages/Webkul/Shop/src/Resources/views/components/datagrid/toolbar.blade.php
Labels: QA Passed

#9573 Fixed Issue #9568
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/views/customers/account/reviews/index.blade.php
  packages/Webkul/Shop/src/Resources/views/partials/pagination.blade.php
  public/themes/shop/default/build/assets/app-1663ec7f.css
  public/themes/shop/default/build/assets/app-e961432d.css
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9583 Street address validation issue fixed
  packages/Webkul/Admin/src/Resources/assets/js/plugins/vee-validate.js
  packages/Webkul/Admin/src/Resources/views/customers/customers/view/addresses/create.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/view/addresses/edit.blade.php
  packages/Webkul/Shop/src/Resources/assets/js/plugins/vee-validate.js
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/address/form.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/addresses/create.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/addresses/edit.blade.php
  public/themes/admin/default/build/assets/app-c8df2f15.js
  public/themes/admin/default/build/assets/app-d9b9ee54.css
  public/themes/admin/default/build/assets/app-e59ccfc6.js
  public/themes/admin/default/build/assets/app-ed47dcd1.css
  public/themes/admin/default/build/manifest.json
  public/themes/shop/default/build/assets/app-5b1bdb47.js
  public/themes/shop/default/build/manifest.json
Labels: In Testing

#9545 Fixed Issue #9543
  packages/Webkul/Shop/src/Http/Controllers/Customer/ForgotPasswordController.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
Labels: Fix Proposed

#9596 Done enhancement #9591
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
Labels: QA Passed

#9593 Fixed empty phone number issue
  packages/Webkul/Admin/src/Http/Controllers/Catalog/CategoryController.php
  packages/Webkul/Admin/src/Http/Controllers/Customers/CustomerController.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php
Labels: QA Passed
