Repository bagisto/bagisto, pull requests merged in 2024-05, with the labels that each got.

#9692 Fixed notification shimmer
  packages/Webkul/Admin/src/Resources/views/components/shimmer/notifications/index.blade.php
  packages/Webkul/Admin/src/Resources/views/notifications/index.blade.php
  public/themes/admin/default/build/assets/app-b7000ee8.css
Labels: QA Passed

#9736 Fixed Issue #9728
  packages/Webkul/Admin/src/Resources/views/customers/customers/view/invoices.blade.php
Labels: QA Passed

#9737 Fixed Catalog rule page issue.
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php
Labels: QA Passed

#9760 Fixed issue #9758
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
Labels: QA Passed

#9750 Fixed theme Customization shimmers
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/category-carousel/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/image-carousel/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/product-carousel/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/services-content/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/category-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/product-carousel.blade.php
Labels: QA Passed

#9738 Added Cart Rule Page Shimmer.
  packages/Webkul/Admin/src/Resources/assets/css/app.css
  packages/Webkul/Admin/src/Resources/views/components/shimmer/marketing/promotions/cart-rules/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
  public/themes/admin/default/build/assets/app-b7000ee8.css
  public/themes/admin/default/build/assets/app-c535a440.css
  public/themes/admin/default/build/assets/app-e152502d.css
  public/themes/admin/default/build/manifest.json
Labels: QA Passed

#9754 :rocket: feat: Added review-attachments zoomer
  packages/Webkul/Shop/src/Resources/views/components/modal/image-zoomer.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
  public/themes/shop/default/build/assets/app-20377ba5.js
  public/themes/shop/default/build/assets/app-2c22a38d.css
  public/themes/shop/default/build/assets/app-59c0c441.js
  public/themes/shop/default/build/assets/app-fd7bdf1e.css
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9778 Fixed configurable product image issue
  packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view/types/configurable.blade.php
Labels: In Testing

#9747 Refactoring Theme section.
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/services-content/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/category-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/footer-links.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/image-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/product-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/services-content.blade.php
  packages/Webkul/Installer/src/Resources/views/installer/index.blade.php
  public/themes/admin/default/build/assets/app-1849ce7e.js
  public/themes/admin/default/build/assets/app-62f5e7b7.css
  public/themes/admin/default/build/assets/app-bfd7cb4f.js
  public/themes/admin/default/build/assets/app-cfcd5ad3.css
  public/themes/admin/default/build/assets/app-e152502d.css
  public/themes/admin/default/build/manifest.json
Labels: QA Passed

#9766 Fixed issue #9764
  packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/bundle.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/grouped.blade.php
  public/themes/admin/default/build/assets/app-1a29d6e4.css
  public/themes/admin/default/build/assets/app-878daf20.js
  public/themes/admin/default/build/assets/app-bfd7cb4f.js
  public/themes/admin/default/build/assets/app-cfcd5ad3.css
  public/themes/admin/default/build/manifest.json
Labels: QA Passed

#9776 Issue #9719 fixed
  UPGRADE.md
  packages/Webkul/Product/src/Type/Configurable.php
  packages/Webkul/Shop/src/Resources/views/products/prices/configurable.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view/types/configurable.blade.php
Labels: QA Passed

#9752 issue: default_address issue fixed.
  packages/Webkul/Admin/src/Resources/views/sales/orders/create/cart/address.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/create/recent-order-items.blade.php
Labels: QA Passed

#9741 Fixed select type attribute view for mobile
  packages/Webkul/Admin/src/Resources/views/sales/invoices/create.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view/types/configurable.blade.php
  public/themes/admin/default/build/assets/app-d119ac0a.css
  public/themes/shop/default/build/assets/app-df61f705.css
Labels: QA Passed

#9774 Fixed issue #9761
  UPGRADE.md
  packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
  packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
Labels: QA Passed

#9773 Fix Social Share For mobile view.
  packages/Webkul/SocialShare/src/Resources/views/share.blade.php
Labels: QA Passed

#9771 Fixed Issue #9763
  packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php
Labels: QA Passed

#9791 Configurable product option redesign
  packages/Webkul/Shop/src/CacheFilters/Large.php
  packages/Webkul/Shop/src/CacheFilters/Medium.php
  packages/Webkul/Shop/src/CacheFilters/Small.php
  packages/Webkul/Shop/src/Resources/views/products/view/types/configurable.blade.php
  public/themes/shop/default/build/assets/app-59c0c441.js
  public/themes/shop/default/build/assets/app-a31a9687.css
  public/themes/shop/default/build/assets/app-c026f8b6.js
  public/themes/shop/default/build/assets/app-df61f705.css
  public/themes/shop/default/build/assets/app-f0bc3de6.css
  public/themes/shop/default/build/assets/app-fd7bdf1e.css
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9822 acl enhancement.
  packages/Webkul/Admin/src/Providers/AdminServiceProvider.php
  packages/Webkul/Admin/src/Resources/views/settings/roles/create.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/roles/edit.blade.php
  packages/Webkul/Core/src/Acl.php
  packages/Webkul/Core/src/Acl/AclItem.php
  packages/Webkul/Core/src/Facades/Acl.php
  packages/Webkul/Core/src/Http/helpers.php
  packages/Webkul/Core/src/Providers/CoreServiceProvider.php
  packages/Webkul/User/src/Http/Middleware/Bouncer.php
  packages/Webkul/User/src/Http/helpers.php
Labels: Conflicts

#9797 Menu Enhancement.
  UPGRADE.md
  packages/Webkul/Admin/src/Providers/AdminServiceProvider.php
  packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/layouts/sidebar/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/layouts/tabs.blade.php
  packages/Webkul/Core/src/Facades/Menu.php
  packages/Webkul/Core/src/Http/helpers.php
  packages/Webkul/Core/src/Menu.php
  packages/Webkul/Core/src/Menu/MenuItem.php
  packages/Webkul/Core/src/Providers/CoreServiceProvider.php
  packages/Webkul/Core/src/Tree.php
  packages/Webkul/Core/tests/Unit/MenuTest.php
  packages/Webkul/Shop/src/Providers/ShopServiceProvider.php
  packages/Webkul/Shop/src/Resources/views/components/layouts/account/navigation.blade.php
Labels: In Testing

#9810 Issue #9796 fixed.
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/category-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/footer-links.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/image-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/product-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/services-content.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/static-content.blade.php
  packages/Webkul/Theme/src/Models/ThemeCustomization.php
  packages/Webkul/Theme/src/Repositories/ThemeCustomizationRepository.php
Labels: QA Passed

#9570 theme: filterable dynamic options.
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/product-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/static-content.blade.php
  public/themes/admin/default/build/assets/app-21d32bb7.js
  public/themes/admin/default/build/assets/app-2cde1b6f.js
  public/themes/admin/default/build/assets/app-911536a8.css
  public/themes/admin/default/build/assets/app-bf32b517.css
  public/themes/admin/default/build/manifest.json
Labels: QA Passed
