Repository bagisto/bagisto, pull requests merged in 2024-06, with the labels that each got.

#9849 fixed #9801 filters overlapping to headers issue
  packages/Webkul/Shop/src/Resources/views/categories/toolbar.blade.php
Labels: QA Passed

#9878 Fixed issue #9875
  packages/Webkul/Admin/src/Resources/views/components/datagrid/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
Labels: Change Request

#9869 Fixed issue #9863
  packages/Webkul/Admin/src/Resources/views/emails/orders/inventory-source.blade.php
  packages/Webkul/Admin/src/Resources/views/emails/orders/shipped.blade.php
  packages/Webkul/Payment/src/Payment/Payment.php
  packages/Webkul/Shop/src/Resources/views/emails/orders/shipped.blade.php
Labels: In Testing

#9874 Fixed issue #9852
  packages/Webkul/Admin/src/Http/Controllers/Customers/AddressController.php
  packages/Webkul/Admin/src/Http/Requests/AddressRequest.php
  packages/Webkul/Admin/src/Http/Requests/CartAddressRequest.php
  packages/Webkul/Shop/src/Http/Controllers/API/AddressController.php
  packages/Webkul/Shop/src/Http/Requests/CartAddressRequest.php
  packages/Webkul/Shop/src/Http/Requests/Customer/AddressRequest.php
Labels: QA Passed

#9882 Done Improvement #9795
  packages/Webkul/Admin/src/Http/Controllers/Catalog/AttributeController.php
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
Labels: QA Passed

#9889 Fixed issue #9885
  packages/Webkul/Admin/src/Resources/assets/js/plugins/admin.js
  public/themes/admin/default/build/assets/app-21d32bb7.js
  public/themes/admin/default/build/assets/app-6155b996.css
  public/themes/admin/default/build/assets/app-8d56797f.js
  public/themes/admin/default/build/assets/app-ba1f45b9.css
  public/themes/admin/default/build/manifest.json
Labels: QA Passed

#9894 Issue #9883 fixed
  packages/Webkul/Admin/src/Resources/assets/js/plugins/vee-validate.js
  packages/Webkul/Shop/src/Resources/assets/js/plugins/vee-validate.js
Labels: QA Passed

#9848 Issue #9845 Fixed.
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
Labels: QA Passed

#9896 Enhancement for vee validate validations.
  packages/Webkul/Admin/src/Resources/assets/js/plugins/vee-validate.js
  packages/Webkul/Shop/src/Resources/assets/js/plugins/vee-validate.js
  public/themes/admin/default/build/assets/app-5c9f2d83.js
  public/themes/admin/default/build/assets/app-819c5abe.css
  public/themes/admin/default/build/assets/app-948e084b.css
  public/themes/admin/default/build/assets/app-c181ae83.js
  public/themes/admin/default/build/manifest.json
  public/themes/shop/default/build/assets/app-10e3decc.js
  public/themes/shop/default/build/assets/app-1a3eb2d9.css
  public/themes/shop/default/build/assets/app-c8273827.js
  public/themes/shop/default/build/assets/app-f5a9d607.css
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9903 Downloadable product add to cart and rating props warning fixed.
  packages/Webkul/Shop/src/Resources/views/components/products/ratings.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view.blade.php
Labels: Change Request

#9905 Fixed Configurable Product Price Issue
  packages/Webkul/Product/src/Repositories/ProductRepository.php
  packages/Webkul/Product/src/Type/Configurable.php
Labels: QA Passed

#9904 Fixed category third level and checkout error message issue
  packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
  packages/Webkul/Shop/src/Http/Controllers/API/OnepageController.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php
  public/themes/admin/default/build/assets/app-5971fea1.css
  public/themes/admin/default/build/assets/app-5c9f2d83.js
  public/themes/admin/default/build/assets/app-819c5abe.css
  public/themes/admin/default/build/assets/app-f0767ae8.js
  public/themes/admin/default/build/manifest.json
Labels: QA Passed

#9862 theme dynamic filter: products and categories.
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/category-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/product-carousel.blade.php
Labels: QA Passed

#9830 :star: Enhancing Installer Package.
  packages/Webkul/Installer/src/Console/Commands/Installer.php
  packages/Webkul/Installer/src/Database/Seeders/Category/CategoryTableSeeder.php
  packages/Webkul/Installer/src/Database/Seeders/Core/CurrencyTableSeeder.php
  packages/Webkul/Installer/src/Database/Seeders/DatabaseSeeder.php
  packages/Webkul/Installer/src/Database/Seeders/ProductTableSeeder.php
  packages/Webkul/Installer/src/Database/Seeders/Shop/ThemeCustomizationTableSeeder.php
  packages/Webkul/Installer/src/Helpers/DatabaseManager.php
  packages/Webkul/Installer/src/Http/Controllers/InstallerController.php
  packages/Webkul/Installer/src/Resources/assets/css/app.css
  packages/Webkul/Installer/src/Resources/assets/images/seeders/products/1.webp
  packages/Webkul/Installer/src/Resources/assets/images/seeders/products/10.webp
  packages/Webkul/Installer/src/Resources/assets/images/seeders/products/11.webp
  packages/Webkul/Installer/src/Resources/assets/images/seeders/products/12.webp
  packages/Webkul/Installer/src/Resources/assets/images/seeders/products/2.webp
  packages/Webkul/Installer/src/Resources/assets/images/seeders/products/3.webp
  packages/Webkul/Installer/src/Resources/assets/images/seeders/products/4.webp
  packages/Webkul/Installer/src/Resources/assets/images/seeders/products/5.webp
  packages/Webkul/Installer/src/Resources/assets/images/seeders/products/6.webp
  packages/Webkul/Installer/src/Resources/assets/images/seeders/products/7.webp
  packages/Webkul/Installer/src/Resources/assets/images/seeders/products/8.webp
  packages/Webkul/Installer/src/Resources/assets/images/seeders/products/9.webp
  packages/Webkul/Installer/src/Resources/lang/ar/app.php
  packages/Webkul/Installer/src/Resources/lang/bn/app.php
  packages/Webkul/Installer/src/Resources/lang/de/app.php
  packages/Webkul/Installer/src/Resources/lang/en/app.php
  packages/Webkul/Installer/src/Resources/lang/es/app.php
  packages/Webkul/Installer/src/Resources/lang/fa/app.php
  packages/Webkul/Installer/src/Resources/lang/fr/app.php
  packages/Webkul/Installer/src/Resources/lang/he/app.php
  packages/Webkul/Installer/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Installer/src/Resources/lang/it/app.php
  packages/Webkul/Installer/src/Resources/lang/ja/app.php
  packages/Webkul/Installer/src/Resources/lang/nl/app.php
  packages/Webkul/Installer/src/Resources/lang/pl/app.php
  packages/Webkul/Installer/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Installer/src/Resources/lang/ru/app.php
  packages/Webkul/Installer/src/Resources/lang/sin/app.php
  packages/Webkul/Installer/src/Resources/lang/tr/app.php
  packages/Webkul/Installer/src/Resources/lang/uk/app.php
  packages/Webkul/Installer/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Installer/src/Resources/views/components/form/control-group/control.blade.php
  packages/Webkul/Installer/src/Resources/views/components/form/control-group/label.blade.php
  packages/Webkul/Installer/src/Resources/views/components/form/index.blade.php
  packages/Webkul/Installer/src/Resources/views/installer/index.blade.php
  packages/Webkul/Installer/src/Routes/web.php
  packages/Webkul/Installer/tailwind.config.js
  public/themes/installer/default/build/assets/app-21e34aa6.js
  public/themes/installer/default/build/assets/app-5243dc7a.js
  public/themes/installer/default/build/assets/app-e0adf3d7.css
  public/themes/installer/default/build/assets/app-f42a86a1.css
  public/themes/installer/default/build/manifest.json
Labels: QA Passed

#9911 Configurable product type class refactorred and optimized
  packages/Webkul/Product/src/Type/AbstractType.php
  packages/Webkul/Product/src/Type/Configurable.php
Labels: QA Passed

#9914 Cart checkout
  packages/Webkul/Shop/src/Resources/views/checkout/onepage/address/customer.blade.php
Labels: QA Passed

#9913 Refactor/Optimize product type
  UPGRADE.md
  packages/Webkul/Admin/src/Http/Controllers/Catalog/ProductController.php
  packages/Webkul/Attribute/src/Repositories/AttributeFamilyRepository.php
  packages/Webkul/Attribute/src/Repositories/AttributeOptionRepository.php
  packages/Webkul/Attribute/src/Repositories/AttributeRepository.php
  packages/Webkul/CMS/src/Repositories/PageRepository.php
  packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php
  packages/Webkul/CatalogRule/src/Repositories/CatalogRuleRepository.php
  packages/Webkul/Category/src/Repositories/CategoryRepository.php
  packages/Webkul/Core/src/Repositories/ChannelRepository.php
  packages/Webkul/Product/src/Repositories/ProductAttributeValueRepository.php
  packages/Webkul/Product/src/Repositories/ProductImageRepository.php
  packages/Webkul/Product/src/Repositories/ProductRepository.php
  packages/Webkul/Product/src/Repositories/ProductVideoRepository.php
  packages/Webkul/Product/src/Type/AbstractType.php
  packages/Webkul/Product/src/Type/Bundle.php
  packages/Webkul/Product/src/Type/Configurable.php
  packages/Webkul/Product/src/Type/Downloadable.php
  packages/Webkul/Product/src/Type/Grouped.php
Labels: QA Passed

#9925 Bundle product option validation issue fixed
  packages/Webkul/Product/src/Type/Bundle.php
  packages/Webkul/Shop/src/Resources/views/components/form/control-group/control.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
Labels: QA Passed

#9916 Added theme column in theme-customisation data grid
  packages/Webkul/Admin/src/DataGrids/Theme/ThemeDataGrid.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
Labels: QA Passed

#9922 Refactor theme
  packages/Webkul/Admin/src/Resources/views/components/shimmer/accordion/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/category-carousel/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/footer-links/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/image-carousel/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/product-carousel/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/services-content/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/static-content/index.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/category-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/footer-links.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/image-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/product-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/services-content.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/static-content.blade.php
  public/themes/admin/default/build/assets/app-bbf8cb07.css
  public/themes/admin/default/build/assets/app-f2aaf3a2.css
  public/themes/admin/default/build/manifest.json
Labels: QA Passed

#9929 Fixed locale switcher for RTL
  packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
Labels: QA Passed

#9938 Fixed transaction page view issue and icon issue in RTL
  packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/pagination.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/index.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/view/invoices.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/view/orders.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/view/reviews.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/reviews/index.blade.php
  packages/Webkul/Admin/src/Resources/views/dashboard/stock-threshold-products.blade.php
  packages/Webkul/Admin/src/Resources/views/dashboard/todays-details.blade.php
  packages/Webkul/Admin/src/Resources/views/notifications/index.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/index.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/transactions/index.blade.php
Labels: QA Passed

#9933 Fixed #9932
  packages/Webkul/Admin/src/Http/Controllers/Sales/OrderController.php
Labels: QA Passed

#9935 Fix cms page datagrid locale issue
  packages/Webkul/Admin/src/DataGrids/CMS/CMSPageDataGrid.php
Labels: QA Passed

#9944 :bug: Fixed Cart page issue.
  packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
  public/themes/shop/default/build/assets/app-5c71c5fd.css
  public/themes/shop/default/build/assets/app-c9b2689a.css
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9950 Fixed multiselect issue
  packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/create/cart/summary.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/create/types/bundle.blade.php
  packages/Webkul/Shop/src/Resources/views/components/form/control-group/control.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view/types/bundle.blade.php
Labels: QA Passed

#9948 few fixes in CLI Installer
  packages/Webkul/Installer/src/Console/Commands/Installer.php
Labels: QA Passed

#9955 Issue #9952 fixed.
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
Labels: QA Passed
