Repository bagisto/bagisto, pull requests merged in 2024-02, with the labels that each got.

#9397 Issue #9396 fixed
  packages/Webkul/Product/src/Repositories/ElasticSearchRepository.php
Labels: QA Passed

#9404 Fixed Issue #9401
  packages/Webkul/Admin/src/Resources/views/settings/currencies/index.blade.php
Labels: QA Passed

#9405 Fix console issue on home page in shop.
  packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php
Labels: QA Passed

#9398 Issue #9369 fixed.
  packages/Webkul/Admin/src/DataGrids/Theme/ThemeDatagrid.php
Labels: QA Passed

#9416 Fixed minor issues
  packages/Webkul/Admin/src/Config/system.php
  packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
  packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
  public/themes/admin/default/build/assets/app-3b5ce4a8.css
  public/themes/admin/default/build/assets/app-744a0a53.js
  public/themes/admin/default/build/assets/app-e59ccfc6.js
  public/themes/admin/default/build/assets/app-e99883f4.css
  public/themes/admin/default/build/manifest.json
Labels: QA Passed

#9412 Issue#9399 video
  packages/Webkul/Admin/src/Http/Requests/ProductForm.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/catalog/products/edit/videos.blade.php
  packages/Webkul/Admin/src/Resources/views/components/media/videos.blade.php
Labels: QA Passed

#9394 :wheelchair: Added class for Order Status Fraud & Pending Payments.
  packages/Webkul/Admin/src/Http/Controllers/Sales/TransactionController.php
  packages/Webkul/Admin/src/Resources/assets/css/app.css
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
  packages/Webkul/Sales/src/Models/Invoice.php
  packages/Webkul/Sales/src/Models/Order.php
  packages/Webkul/Sales/src/Repositories/InvoiceRepository.php
  packages/Webkul/Sales/src/Repositories/OrderRepository.php
  public/themes/admin/default/build/assets/app-414236fd.js
  public/themes/admin/default/build/assets/app-92ace43a.css
Labels: QA Passed, Fix Proposed

#9431 Added XLSX file support in export
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/components/datagrid/export/index.blade.php
  packages/Webkul/DataGrid/src/DataGrid.php
Labels: QA Passed

#9438 Added missing translation
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
Labels: QA Passed

#9440 Shorted all shop locales arrays keys alphabetically
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
Labels: QA Passed

#9441 Fix Console issue in Shop Home page.
  packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php
Labels: QA Passed

#9444 Fixed Issue #9442
  packages/Webkul/Installer/src/Database/Seeders/Shop/ThemeCustomizationTableSeeder.php
Labels: QA Passed

#9445 Theme slider add label issue.
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/image-carousel.blade.php
Labels: QA Passed

#9452 theme datagrid results count issue fixed.
  packages/Webkul/Admin/src/DataGrids/Theme/ThemeDatagrid.php
Labels: QA Passed

#9453 fix issue on product data grid product type lang not rendered.
  packages/Webkul/Admin/src/DataGrids/Catalog/ProductDataGrid.php
Labels: QA Passed

#9454 In mobile view there is show only default image after change from config.
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php
Labels: QA Passed

#9457 Added Zoom on Theme Customisation Static Content Hover.
  packages/Webkul/Installer/src/Database/Seeders/Shop/ThemeCustomizationTableSeeder.php
Labels: In Testing

#9449 Fixed error message not set issue in customer edit modal made it component
  packages/Webkul/Admin/src/Http/Controllers/Customers/CustomerController.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/index.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php
  packages/Webkul/Admin/src/Routes/customers-routes.php
  packages/Webkul/Admin/tests/Feature/Customers/CustomersTest.php
  public/themes/admin/default/build/assets/app-14c5e344.css
  public/themes/admin/default/build/assets/app-414236fd.js
  public/themes/admin/default/build/assets/app-744a0a53.js
  public/themes/admin/default/build/assets/app-8c30b7d8.js
  public/themes/admin/default/build/assets/app-92ace43a.css
  public/themes/admin/default/build/assets/app-f60ad056.css
  public/themes/admin/default/build/manifest.json
Labels: QA Passed

#9447 Fixing Header in top in shop section.
  packages/Webkul/Shop/src/Resources/views/components/dropdown/index.blade.php
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/index.blade.php
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/index.blade.php
  public/themes/shop/default/build/assets/app-340e0f29.js
  public/themes/shop/default/build/assets/app-39080016.css
  public/themes/shop/default/build/assets/app-ad33e4b7.css
  public/themes/shop/default/build/manifest.json
Labels: QA Passed, Fix Proposed

#9411 Remove unused statement.
  packages/Webkul/Product/src/Repositories/ProductRepository.php
Labels: Change Request

#9515 Fixed issue #9514
  packages/Webkul/Admin/src/Config/system.php
Labels: QA Passed

#9505 Fixed order status filter and event date filter
  packages/Webkul/Admin/src/DataGrids/Marketing/Communications/EventDataGrid.php
  packages/Webkul/Admin/src/DataGrids/Sales/OrderDataGrid.php
Labels: QA Passed

#9509 Datagrid issue fixed in hindi locale.
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
Labels: QA Passed

#9510 Issue #9500 fixed.
  packages/Webkul/Shop/src/Resources/views/components/range-slider/index.blade.php
Labels: QA Passed

#9511 Fixed customer address issues
  packages/Webkul/Admin/src/Resources/views/customers/addresses/edit.blade.php
  packages/Webkul/Shop/src/Resources/views/components/shimmer/form/control-group/index.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/addresses/create.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/addresses/edit.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/addresses/index.blade.php
  public/themes/shop/default/build/assets/app-3669f6b9.css
  public/themes/shop/default/build/assets/app-c95493d4.css
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9503 Arabic slider.
  packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php
  public/themes/shop/default/build/assets/app-655eb5a9.js
  public/themes/shop/default/build/assets/app-6c1560ad.js
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9541 Fix Shop Datagrid UI
  packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/downloadable.blade.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/views/customers/account/downloadable_products/index.blade.php
  public/themes/shop/default/build/assets/app-340e0f29.js
  public/themes/shop/default/build/assets/app-744bc255.js
  public/themes/shop/default/build/manifest.json
Labels: QA Passed
