Repository bagisto/bagisto, pull requests merged in 2024-01, with the labels that each got.

#9273 [Fixed: installer channel's locales creation issue.]
  packages/Webkul/Installer/src/Database/Seeders/Core/ChannelTableSeeder.php
Labels: In Testing

#9266 create separate plugin for admin package vee-validate
  packages/Webkul/Admin/src/Resources/assets/js/app.js
  packages/Webkul/Admin/src/Resources/assets/js/plugins/draggable.js
  packages/Webkul/Admin/src/Resources/assets/js/plugins/vee-validate.js
  packages/Webkul/Admin/src/Resources/assets/locales/hi_IN.json
  packages/Webkul/Admin/src/Resources/assets/locales/sin.json
  public/themes/admin/default/build/assets/app-2e685c71.js
  public/themes/admin/default/build/assets/app-74d8007e.js
  public/themes/admin/default/build/manifest.json
Labels: Fix Proposed

#9291 fixed issue #9280
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/top.blade.php
  public/themes/shop/default/build/assets/app-94c96181.css
  public/themes/shop/default/build/assets/app-b48bfd54.js
  public/themes/shop/default/build/assets/app-d643bda6.css
  public/themes/shop/default/build/assets/app-ee3ef8bb.js
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9281 Fixed cart rule condition input fields ui
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
  public/themes/admin/default/build/assets/app-59b5b6f1.js
  public/themes/admin/default/build/assets/app-f429e003.css
Labels: QA Passed

#9203 Added label classes in shop package
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/index.blade.php
  packages/Webkul/Shop/src/Resources/assets/css/app.css
  packages/Webkul/Shop/src/Resources/views/components/example.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/addresses/index.blade.php
  packages/Webkul/Shop/tailwind.config.js
  public/themes/shop/default/build/assets/app-0ea4c703.css
  public/themes/shop/default/build/assets/app-dca6a5a2.js
Labels: Conflicts

#9301 fixed issue #9299
  packages/Webkul/Shop/src/Resources/assets/css/app.css
  public/themes/shop/default/build/assets/app-0ea4c703.css
  public/themes/shop/default/build/assets/app-4614b2f4.css
  public/themes/shop/default/build/assets/app-94c96181.css
  public/themes/shop/default/build/assets/app-dca6a5a2.js
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9293 fixed console error in product view on variant change
  packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
Labels: QA Passed

#9294 fix: #9275 fixed shop compiled flag issue
  packages/Webkul/Shop/package.json
  packages/Webkul/Shop/vite.config.js
  public/themes/admin/default/build/assets/app-2138a625.js
  public/themes/admin/default/build/assets/app-6187836c.css
  public/themes/admin/default/build/assets/app-c19fd257.css
  public/themes/admin/default/build/assets/app-f24b1604.js
  public/themes/admin/default/build/manifest.json
  public/themes/shop/default/build/assets/app-4614b2f4.css
  public/themes/shop/default/build/assets/app-6b7da7ce.css
  public/themes/shop/default/build/assets/app-744bc255.js
  public/themes/shop/default/build/assets/app-ee3ef8bb.js
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9302 Fixed issue #9292
  packages/Webkul/Installer/src/Resources/views/installer/index.blade.php
Labels: QA Passed

#9341 Fixed issue #9329
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php
Labels: QA Passed

#9339 Validate user roll
  packages/Webkul/Admin/src/Http/Controllers/Settings/RoleController.php
  packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
Labels: QA Passed

#9354 Done improvement #9334
  packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/configuration/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
Labels: QA Passed

#9338 sorted arrays in locales alphabetically
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
Labels: QA Passed

#9351 extra period fixed
  packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
Labels: QA Passed

#9347 Fixed product image resolution text and footer text
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/views/components/layouts/footer/index.blade.php
Labels: QA Passed

#9353 Fixed some minor issues
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php
Labels: QA Passed

#9355 Fixed dashboard console error in top selling products
  packages/Webkul/Admin/src/Resources/views/dashboard/top-selling-products.blade.php
Labels: In Testing

#9332 Fixed issue #9317
  packages/Webkul/Admin/src/Config/system.php
  packages/Webkul/Core/src/Traits/CoreConfigField.php
Labels: QA Passed

#9349 Fixed issue #9328
  packages/Webkul/Admin/src/Http/Controllers/Settings/ThemeController.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/static-content.blade.php
  packages/Webkul/Shop/src/Resources/views/components/carousel/index.blade.php
  packages/Webkul/Theme/src/Repositories/ThemeCustomizationRepository.php
Labels: Critical
