Repository bagisto/bagisto, pull requests merged in 2024-09, with the labels that each got.

#10087 Fix issue #10080 - Installation fails if password contains special ch…
  packages/Webkul/Installer/src/Console/Commands/Installer.php
Labels: Fix Proposed

#10063 Added "Bahraini Dinar" (BHD) currency
  packages/Webkul/Installer/src/Console/Commands/Installer.php
  packages/Webkul/Installer/src/Database/Seeders/Core/CurrencyTableSeeder.php
  packages/Webkul/Installer/src/Resources/lang/ar/app.php
  packages/Webkul/Installer/src/Resources/lang/bn/app.php
  packages/Webkul/Installer/src/Resources/lang/de/app.php
  packages/Webkul/Installer/src/Resources/lang/en/app.php
  packages/Webkul/Installer/src/Resources/lang/es/app.php
  packages/Webkul/Installer/src/Resources/lang/fa/app.php
  packages/Webkul/Installer/src/Resources/lang/fr/app.php
  packages/Webkul/Installer/src/Resources/lang/he/app.php
  packages/Webkul/Installer/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Installer/src/Resources/lang/it/app.php
  packages/Webkul/Installer/src/Resources/lang/ja/app.php
  packages/Webkul/Installer/src/Resources/lang/nl/app.php
  packages/Webkul/Installer/src/Resources/lang/pl/app.php
  packages/Webkul/Installer/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Installer/src/Resources/lang/ru/app.php
  packages/Webkul/Installer/src/Resources/lang/sin/app.php
  packages/Webkul/Installer/src/Resources/lang/tr/app.php
  packages/Webkul/Installer/src/Resources/lang/uk/app.php
  packages/Webkul/Installer/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Installer/src/Resources/views/installer/index.blade.php
Labels: In Testing

#10117 Closing tag Added.
  packages/Webkul/Admin/src/Resources/views/components/media/images.blade.php
Labels: QA Passed

#10110 Feature Added #10072
  packages/Webkul/Admin/src/Config/system.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
Labels: Fix Proposed

#10099 Fixed Issue #10082
  packages/Webkul/Admin/src/Resources/views/sales/invoices/pdf.blade.php
Labels: QA Passed
