Repository bagisto/bagisto, pull requests merged in 2024-04, with the labels that each got.

#9611 Fixed Issue #9610
  packages/Webkul/SocialShare/src/Resources/views/links/email.blade.php
  packages/Webkul/SocialShare/src/Resources/views/links/facebook.blade.php
  packages/Webkul/SocialShare/src/Resources/views/links/linkedin.blade.php
  packages/Webkul/SocialShare/src/Resources/views/links/pinterest.blade.php
  packages/Webkul/SocialShare/src/Resources/views/links/twitter.blade.php
Labels: QA Passed

#9613 Fixed Issue #9612
  packages/Webkul/Admin/src/Http/Controllers/Catalog/CategoryController.php
Labels: QA Passed

#9647 Fixed issue #9646
  packages/Webkul/Shop/src/Resources/views/customers/reset-password.blade.php
Labels: QA Passed

#9648 Fix flash message in product add to cart.
  packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/views/components/products/card.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view.blade.php
Labels: QA Passed

#9651 Fixed issue #9645
  packages/Webkul/Sales/src/Models/Order.php
Labels: QA Passed

#9656 Fixed order status label issue
  packages/Webkul/Admin/src/Resources/views/components/example.blade.php
  public/themes/admin/default/build/assets/app-1f60571f.css
  public/themes/admin/default/build/assets/app-48573b34.js
  public/themes/admin/default/build/assets/app-e2b82be7.js
  public/themes/admin/default/build/assets/app-fc0d639e.css
  public/themes/admin/default/build/manifest.json
Labels: QA Passed

#9652 Fixed #9649 - Spanish Translations corrected
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Installer/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
Labels: Change Request

#9638 Fixed order creation issue on inventory Zero
  packages/Webkul/Admin/src/Http/Resources/ProductResource.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/create/cart/items.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/create/compare-items.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/create/recent-order-items.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/create/wishlist-items.blade.php
Labels: QA Passed

#9635 Fixed Issue #9632
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/top.blade.php
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php
Labels: QA Passed

#9629 Remove translation from installer local.
  packages/Webkul/Installer/src/Resources/lang/ar/app.php
  packages/Webkul/Installer/src/Resources/lang/bn/app.php
  packages/Webkul/Installer/src/Resources/lang/de/app.php
  packages/Webkul/Installer/src/Resources/lang/en/app.php
  packages/Webkul/Installer/src/Resources/lang/es/app.php
  packages/Webkul/Installer/src/Resources/lang/fa/app.php
  packages/Webkul/Installer/src/Resources/lang/fr/app.php
  packages/Webkul/Installer/src/Resources/lang/he/app.php
  packages/Webkul/Installer/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Installer/src/Resources/lang/it/app.php
  packages/Webkul/Installer/src/Resources/lang/ja/app.php
  packages/Webkul/Installer/src/Resources/lang/nl/app.php
  packages/Webkul/Installer/src/Resources/lang/pl/app.php
  packages/Webkul/Installer/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Installer/src/Resources/lang/ru/app.php
  packages/Webkul/Installer/src/Resources/lang/sin/app.php
  packages/Webkul/Installer/src/Resources/lang/tr/app.php
  packages/Webkul/Installer/src/Resources/lang/uk/app.php
  packages/Webkul/Installer/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Installer/src/Resources/views/installer/index.blade.php
Labels: QA Passed

#9628 Fixed customer view page data-grids
  packages/Webkul/Admin/src/DataGrids/Customers/View/ReviewDatagrid.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/view/notes.blade.php
  packages/Webkul/Admin/src/Resources/views/customers/customers/view/reviews.blade.php
  public/themes/admin/default/build/assets/app-ead8cfb9.css
Labels: QA Passed

#9623 Fixed address card shimmer for checkout page
  packages/Webkul/Shop/src/Resources/views/checkout/login.blade.php
  packages/Webkul/Shop/src/Resources/views/components/shimmer/checkout/onepage/address.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/addresses/index.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/reviews/index.blade.php
  packages/Webkul/Shop/src/Resources/views/customers/account/wishlist/index.blade.php
  packages/Webkul/Shop/src/Resources/views/home/index.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view.blade.php
  packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
  public/themes/shop/default/build/assets/app-0ba43a0d.css
  public/themes/shop/default/build/assets/app-dc90ebc6.css
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9658 Fixed Translation Issue in Payment method.
  packages/Webkul/Payment/src/Payment/MoneyTransfer.php
Labels: QA Passed

#9642 Fix address formatting and Fixed issue in customer view blade template
  packages/Webkul/Admin/src/Resources/views/customers/customers/view.blade.php
  public/themes/admin/default/build/assets/app-135a48c7.css
Labels: QA Passed

#9619 Fixed minor issues
  packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/channels/create.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php
Labels: QA Passed

#9640 [v2.2] Added Contact us page.
  packages/Webkul/Admin/tests/Feature/Cms/CmsTest.php
  packages/Webkul/Installer/src/Database/Seeders/CMS/CMSPagesTableSeeder.php
  packages/Webkul/Installer/src/Database/Seeders/Shop/ThemeCustomizationTableSeeder.php
  packages/Webkul/Shop/src/Http/Controllers/HomeController.php
  packages/Webkul/Shop/src/Http/Requests/ContactRequest.php
  packages/Webkul/Shop/src/Mail/ContactUs.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/views/customers/sign-up.blade.php
  packages/Webkul/Shop/src/Resources/views/emails/contact-us.blade.php
  packages/Webkul/Shop/src/Resources/views/home/contact-us.blade.php
  packages/Webkul/Shop/src/Routes/store-front-routes.php
Labels: QA Passed

#9661 Add shimmer to the topbar in the shop section.
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/top.blade.php
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php
  public/themes/shop/default/build/assets/app-20377ba5.js
  public/themes/shop/default/build/assets/app-9e712869.css
  public/themes/shop/default/build/assets/app-c026f8b6.js
  public/themes/shop/default/build/assets/app-c736495c.css
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9668 Fix export button styling in datagrid export component on loading.
  packages/Webkul/Admin/src/Resources/views/components/datagrid/export/index.blade.php
Labels: QA Passed

#9663 Fix issue #9662
  packages/Webkul/Checkout/src/Cart.php
Labels: QA Passed

#9681 Fixed Issue #9680
  packages/Webkul/Admin/src/Resources/views/components/quantity-changer/index.blade.php
  packages/Webkul/Shop/src/Resources/views/components/quantity-changer/index.blade.php
Labels: QA Passed

#9675 fixed Issue #9673
  packages/Webkul/Customer/src/Repositories/CustomerAddressRepository.php
Labels: QA Passed

#9672 Estimate shipping and tax implemented
  packages/Webkul/Checkout/src/Cart.php
  packages/Webkul/Checkout/src/Database/Migrations/2024_04_16_144400_add_cart_id_column_in_cart_shipping_rates_table.php
  packages/Webkul/Checkout/src/Models/Cart.php
  packages/Webkul/Shipping/src/Shipping.php
  packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
  packages/Webkul/Shop/src/Resources/lang/ar/app.php
  packages/Webkul/Shop/src/Resources/lang/bn/app.php
  packages/Webkul/Shop/src/Resources/lang/de/app.php
  packages/Webkul/Shop/src/Resources/lang/en/app.php
  packages/Webkul/Shop/src/Resources/lang/es/app.php
  packages/Webkul/Shop/src/Resources/lang/fa/app.php
  packages/Webkul/Shop/src/Resources/lang/fr/app.php
  packages/Webkul/Shop/src/Resources/lang/he/app.php
  packages/Webkul/Shop/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Shop/src/Resources/lang/it/app.php
  packages/Webkul/Shop/src/Resources/lang/ja/app.php
  packages/Webkul/Shop/src/Resources/lang/nl/app.php
  packages/Webkul/Shop/src/Resources/lang/pl/app.php
  packages/Webkul/Shop/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Shop/src/Resources/lang/ru/app.php
  packages/Webkul/Shop/src/Resources/lang/sin/app.php
  packages/Webkul/Shop/src/Resources/lang/tr/app.php
  packages/Webkul/Shop/src/Resources/lang/uk/app.php
  packages/Webkul/Shop/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
  packages/Webkul/Shop/src/Resources/views/checkout/cart/summary.blade.php
  packages/Webkul/Shop/src/Resources/views/checkout/cart/summary/estimate-shipping.blade.php
  packages/Webkul/Shop/src/Resources/views/components/accordion/index.blade.php
  packages/Webkul/Shop/src/Routes/api.php
  packages/Webkul/Shop/tests/Feature/Checkout/CheckoutTest.php
  public/themes/shop/default/build/assets/app-20377ba5.js
  public/themes/shop/default/build/assets/app-54dcdf25.css
  public/themes/shop/default/build/assets/app-9e712869.css
  public/themes/shop/default/build/assets/app-c026f8b6.js
  public/themes/shop/default/build/manifest.json
Labels: In Testing

#9689 Fixed issue #9687
  packages/Webkul/Shop/src/Resources/views/home/contact-us.blade.php
Labels: QA Passed

#9688 Implement feature #9685
  packages/Webkul/Admin/src/Resources/views/components/tree/view.blade.php
Labels: QA Passed

#9626 Add contact email configuration
  config/mail.php
  packages/Webkul/Admin/src/Config/system.php
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/emails/layout.blade.php
  packages/Webkul/Core/src/Core.php
  packages/Webkul/Shop/src/Resources/views/emails/layout.blade.php
Labels: QA Passed

#9671 Fixing issue in regex type validation in attribute page.
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/edit.blade.php
Labels: QA Passed

#9691 Fixed Issue #9679
  packages/Webkul/Admin/src/Resources/views/sales/orders/create/cart/items.blade.php
Labels: QA Passed

#9694 Update Contribution Guide.
  CONTRIBUTING.md
Labels: QA Passed

#9696 Fix page shimmer effect on setting section.
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/account/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/attributes/create.blade.php
  packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php
  packages/Webkul/Admin/src/Resources/views/cms/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/taxes/rates/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/category-carousel/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/footer-links/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/image-carousel/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/product-carousel/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/services-content/index.blade.php
  packages/Webkul/Admin/src/Resources/views/components/shimmer/settings/themes/static-content/index.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/communications/campaigns/create.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/communications/campaigns/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/communications/templates/create.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/communications/templates/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/cart-rules/create.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
  packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/sales/refunds/view.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/channels/create.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/data-transfer/imports/create.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/data-transfer/imports/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/data-transfer/imports/import.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/inventory-sources/create.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/inventory-sources/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/roles/create.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/roles/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/taxes/rates/create.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/taxes/rates/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/category-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/footer-links.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/image-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/product-carousel.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/services-content.blade.php
  packages/Webkul/Admin/src/Resources/views/settings/themes/edit/static-content.blade.php
  public/themes/admin/default/build/assets/app-79cd2b70.css
  public/themes/admin/default/build/assets/app-96ea03aa.css
  public/themes/admin/default/build/manifest.json
Labels: QA Passed

#9702 Fixed issue #9701
  packages/Webkul/Admin/src/Http/Controllers/Marketing/Promotions/CartRuleCouponController.php
  packages/Webkul/Admin/src/Routes/marketing-routes.php
Labels: QA Passed

#9703 Fixed category banner issue
  packages/Webkul/Admin/src/Http/Controllers/Catalog/ProductController.php
  packages/Webkul/Shop/src/Resources/views/categories/view.blade.php
  public/themes/shop/default/build/assets/app-54dcdf25.css
  public/themes/shop/default/build/assets/app-6cba5fde.css
  public/themes/shop/default/build/assets/app-b5d5b2b8.js
  public/themes/shop/default/build/assets/app-c026f8b6.js
  public/themes/shop/default/build/manifest.json
Labels: QA Passed

#9710 Fixed issue #9707
  packages/Webkul/Admin/src/Config/system.php
Labels: QA Passed

#9715 Fixed Issue #9714
  packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
Labels: QA Passed

#9716 Fixed issue #9713
  packages/Webkul/Admin/src/Resources/lang/ar/app.php
  packages/Webkul/Admin/src/Resources/lang/bn/app.php
  packages/Webkul/Admin/src/Resources/lang/de/app.php
  packages/Webkul/Admin/src/Resources/lang/en/app.php
  packages/Webkul/Admin/src/Resources/lang/es/app.php
  packages/Webkul/Admin/src/Resources/lang/fa/app.php
  packages/Webkul/Admin/src/Resources/lang/fr/app.php
  packages/Webkul/Admin/src/Resources/lang/he/app.php
  packages/Webkul/Admin/src/Resources/lang/hi_IN/app.php
  packages/Webkul/Admin/src/Resources/lang/it/app.php
  packages/Webkul/Admin/src/Resources/lang/ja/app.php
  packages/Webkul/Admin/src/Resources/lang/nl/app.php
  packages/Webkul/Admin/src/Resources/lang/pl/app.php
  packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
  packages/Webkul/Admin/src/Resources/lang/ru/app.php
  packages/Webkul/Admin/src/Resources/lang/sin/app.php
  packages/Webkul/Admin/src/Resources/lang/tr/app.php
  packages/Webkul/Admin/src/Resources/lang/uk/app.php
  packages/Webkul/Admin/src/Resources/lang/zh_CN/app.php
  packages/Webkul/Admin/src/Resources/views/sales/orders/create/cart/address/form.blade.php
Labels: QA Passed

#9727 Refactor profile validation rules in ProfileRequest.php
  packages/Webkul/Shop/src/Http/Requests/Customer/ProfileRequest.php
Labels: QA Passed

#9712 Fixed issue #9660
  packages/Webkul/Admin/src/Resources/views/customers/customers/view/invoices.blade.php
  packages/Webkul/Shop/src/Resources/views/components/layouts/header/mobile/index.blade.php
  public/themes/admin/default/build/assets/app-25c0197d.js
  public/themes/admin/default/build/assets/app-bfd7cb4f.js
  public/themes/admin/default/build/assets/app-ee45ec40.css
  public/themes/admin/default/build/manifest.json
  public/themes/shop/default/build/assets/app-0f2f858c.css
  public/themes/shop/default/build/assets/app-2cc44ef4.css
  public/themes/shop/default/build/assets/app-9ea6c972.js
Labels: Fix Proposed

#9706 Fixed issue #9705
  packages/Webkul/Admin/src/Resources/views/catalog/products/edit/types/bundle.blade.php
Labels: QA Passed
